import * as THREE from "three";
import { RaceAudio,type AudioSettings } from "./audio";
import { GAME_MODES,RIVAL_NAMES,SHIPS,STORY_EVENTS,TRACKS,type GameModeId,type ShipSpec } from "./game-data";
import { advanceSpeed,clamp,deadzone } from "./mechanics";
import { ENERGY_RANGES,GAP_RANGES,MAGNETIC_RANGES,TRACK_POINTS,gapLift,isEnergyZone,isGap,magneticBank,progressInRange,trackSector } from "./track-data";
import { INITIAL_SNAPSHOT,type InputMode,type RaceSnapshot } from "./types";

type ControlState={steer:number;throttle:number;brake:number;boost:boolean;map:boolean;mode:InputMode};
type Rival={root:THREE.Group;name:string;distance:number;speed:number;lane:number;targetLane:number;decisionTimer:number;color:number};
type VrMenuStep="mode"|"ship"|"track"|"results";
const CYAN=0x69f6ff,AMBER=0xffc25e,MAGENTA=0xff3e93,TRACK_WIDTH=48,TOTAL_LAPS=3,SAMPLES=520;

function signedTrackDelta(a:number,b:number,length:number){let delta=(a-b)%length;if(delta>length/2)delta-=length;if(delta<-length/2)delta+=length;return delta;}

function makeTrack(){return new THREE.CatmullRomCurve3(TRACK_POINTS.map(point=>new THREE.Vector3(...point)),true,"centripetal");}

function frame(curve:THREE.CatmullRomCurve3,progress:number){
  const p=((progress%1)+1)%1,center=curve.getPointAt(p),forward=curve.getTangentAt(p).normalize();
  const worldUp=Math.abs(forward.y)>.94?new THREE.Vector3(0,0,1):new THREE.Vector3(0,1,0);
  const right=forward.clone().cross(worldUp).normalize(),up=right.clone().cross(forward).normalize(),bank=magneticBank(p);
  right.applyAxisAngle(forward,bank);up.applyAxisAngle(forward,bank);
  const matrix=new THREE.Matrix4().makeBasis(right,up,forward.clone().negate());
  return {center,forward,right,up,bank,quaternion:new THREE.Quaternion().setFromRotationMatrix(matrix)};
}

function createTrack(curve:THREE.CatmullRomCurve3){
  const positions:number[]=[],colors:number[]=[],indices:number[]=[];const base=new THREE.Color(0x0b2530),stripe=new THREE.Color(0x174657);
  for(let i=0;i<=SAMPLES;i++){const progress=i/SAMPLES,f=frame(curve,progress),magnetic=MAGNETIC_RANGES.some(([start,end])=>progressInRange(progress,[start,end]));for(let lane=0;lane<=6;lane++){const point=f.center.clone().addScaledVector(f.right,-TRACK_WIDTH/2+lane*TRACK_WIDTH/6).addScaledVector(f.up,-.07);positions.push(point.x,point.y,point.z);const color=magnetic?new THREE.Color(0x452067):lane===0||lane===6||(i%18<2&&lane===3)?stripe:base;colors.push(color.r,color.g,color.b);}}
  for(let i=0;i<SAMPLES;i++){const progress=(i+.5)/SAMPLES;if(isGap(progress))continue;for(let lane=0;lane<6;lane++){const a=i*7+lane,b=a+1,c=a+7,d=c+1;indices.push(a,c,b,b,c,d);}}
  const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute("color",new THREE.Float32BufferAttribute(colors,3));geometry.setIndex(indices);geometry.computeVertexNormals();
  return new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({vertexColors:true,metalness:.82,roughness:.29,emissive:0x02090f,side:THREE.DoubleSide}));
}

function tunnelHasClearance(curve:THREE.CatmullRomCurve3,progress:number){
  const center=curve.getPointAt(progress),minimumClearance=TRACK_WIDTH*1.2;
  for(let sample=0;sample<260;sample++){
    const otherProgress=sample/260,separation=Math.abs(otherProgress-progress),circularSeparation=Math.min(separation,1-separation);
    if(circularSeparation<.04)continue;
    if(center.distanceToSquared(curve.getPointAt(otherProgress))<minimumClearance*minimumClearance)return false;
  }
  return true;
}

export function createRacer(spec:ShipSpec,variant=0,cockpit=false){
  const root=new THREE.Group(),accent=new THREE.Color(spec.accent),shell=new THREE.MeshPhysicalMaterial({color:spec.color,metalness:.92,roughness:.18,clearcoat:1,clearcoatRoughness:.08,emissive:accent,emissiveIntensity:.12}),shellLight=new THREE.MeshPhysicalMaterial({color:new THREE.Color(spec.color).lerp(new THREE.Color(0xffffff),.2),metalness:.86,roughness:.2,clearcoat:1,emissive:accent,emissiveIntensity:.08}),dark=new THREE.MeshStandardMaterial({color:0x01060b,metalness:.9,roughness:.23}),glow=new THREE.MeshBasicMaterial({color:accent,toneMapped:false}),glass=new THREE.MeshPhysicalMaterial({color:0x061a24,metalness:.12,roughness:.04,transmission:.42,transparent:true,opacity:.82,clearcoat:1,emissive:accent,emissiveIntensity:.24});
  root.name=spec.name;root.userData.shipId=spec.id;root.userData.variant=variant;
  const planform=(points:Array<[number,number]>,thickness:number,material:THREE.Material,y=.18)=>{const shape=new THREE.Shape();points.forEach(([x,z],index)=>index?shape.lineTo(x,z):shape.moveTo(x,z));shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:true,bevelSegments:2,bevelSize:.07,bevelThickness:.05,curveSegments:4});geometry.center();geometry.rotateX(Math.PI/2);const mesh=new THREE.Mesh(geometry,material);mesh.position.y=y;root.add(mesh);return mesh;};
  const plate=(width:number,height:number,length:number,x:number,y:number,z:number,material:THREE.Material,ry=0)=>{const mesh=new THREE.Mesh(new THREE.BoxGeometry(width,height,length,2,1,3),material);mesh.position.set(x,y,z);mesh.rotation.y=ry;root.add(mesh);return mesh;};
  const engine=(x:number,z:number,radius=.28,length=.92)=>{const housing=new THREE.Mesh(new THREE.CylinderGeometry(radius*.88,radius*1.2,length,20,1,false),dark),rim=new THREE.Mesh(new THREE.TorusGeometry(radius*.82,.055,8,20),shellLight),core=new THREE.Mesh(new THREE.CircleGeometry(radius*.62,20),glow);housing.rotation.x=rim.rotation.x=core.rotation.x=Math.PI/2;housing.position.set(x,.29,z);rim.position.set(x,.29,z+length*.51);core.position.set(x,.29,z+length*.525);root.add(housing,rim,core);};
  const lightRail=(x:number,z:number,length:number,ry=0)=>{const rail=plate(.055,.045,length,x,.31,z,glow,ry);rail.renderOrder=2;return rail;};
  const canopy=(x=0,z=-.42,sx=.72,sz=1.05)=>{if(cockpit)return;const bubble=new THREE.Mesh(new THREE.SphereGeometry(.62,28,14,0,Math.PI*2,0,Math.PI/2),glass);bubble.scale.set(sx,.62,sz);bubble.position.set(x,.69,z);root.add(bubble);const collar=new THREE.Mesh(new THREE.TorusGeometry(.43,.055,8,28,Math.PI),dark);collar.rotation.x=Math.PI/2;collar.rotation.z=Math.PI;collar.scale.x=sx/.72;collar.position.set(x,.54,z+.22);root.add(collar);};
  if(variant===0){planform([[0,-3.1],[.52,-2.15],[2.55,-.35],[2.18,.72],[.9,.36],[.72,2.25],[0,2.65],[-.72,2.25],[-.9,.36],[-2.18,.72],[-2.55,-.35],[-.52,-2.15]],.2,shell,.2);planform([[0,-2.72],[.36,-1.9],[.55,1.72],[0,2.2],[-.55,1.72],[-.36,-1.9]],.3,shellLight,.39);canopy();for(const side of [-1,1]){engine(side*.86,1.92,.3);lightRail(side*1.74,.05,2.25,side*.2);plate(.1,.4,1.15,side*1.16,.54,.72,dark,side*.18);}}
  else if(variant===1){planform([[0,-3.35],[.34,-2.18],[2.7,-.72],[1.7,.15],[.72,.18],[.48,2.36],[0,2.7],[-.48,2.36],[-.72,.18],[-1.7,.15],[-2.7,-.72],[-.34,-2.18]],.13,shell,.18);planform([[0,-2.95],[.28,-1.65],[.48,1.82],[0,2.22],[-.48,1.82],[-.28,-1.65]],.22,dark,.31);canopy(0,-.58,.54,.94);for(const side of [-1,1]){engine(side*.58,1.98,.21,.82);lightRail(side*1.72,-.72,2.25,side*.62);const fin=plate(.07,.66,1.2,side*1.48,.51,-.15,dark,side*.38);fin.rotation.z=side*.2;}}
  else if(variant===2){planform([[0,-2.72],[1.18,-2.05],[2.5,-1.06],[2.58,1.78],[1.64,2.48],[.58,2.28],[0,2.62],[-.58,2.28],[-1.64,2.48],[-2.58,1.78],[-2.5,-1.06],[-1.18,-2.05]],.38,shell,.25);planform([[0,-2.45],[.7,-1.68],[.92,1.36],[0,1.9],[-.92,1.36],[-.7,-1.68]],.4,shellLight,.52);canopy(0,-.25,.9,1.08);for(const side of [-1,1]){plate(.74,.55,3.5,side*1.68,.36,.46,dark);plate(.17,.24,3.25,side*2.13,.42,.38,shellLight);engine(side*1.7,2.03,.4,1.06);lightRail(side*2.22,.25,2.95);}plate(1.06,.18,.62,0,.62,1.78,dark);}
  else if(variant===3){for(const side of [-1,1]){planform([[side*.22,-2.72],[side*1.16,-2.22],[side*1.55,-.15],[side*1.3,2.25],[side*.42,2.62]],.24,shell,.22);const hull=new THREE.Mesh(new THREE.CapsuleGeometry(.42,3.55,10,22),shellLight);hull.rotation.x=Math.PI/2;hull.position.set(side*.84,.46,-.02);root.add(hull);engine(side*.84,2.08,.35,1.05);const pulse=new THREE.Mesh(new THREE.TorusGeometry(.47,.075,10,32),glow);pulse.position.set(side*.84,.47,1.72);root.add(pulse);lightRail(side*1.3,-.08,2.4,side*.06);}plate(1.3,.14,1.65,0,.28,.28,dark);canopy(0,-.42,.58,.88);}
  else{planform([[0,-3.05],[.46,-2.15],[1.15,-1.52],[2.58,-1.08],[1.82,.18],[2.18,1.7],[.72,1.1],[.58,2.46],[0,2.72],[-.58,2.46],[-.72,1.1],[-2.18,1.7],[-1.82,.18],[-2.58,-1.08],[-1.15,-1.52],[-.46,-2.15]],.18,shell,.2);planform([[0,-2.7],[.35,-1.72],[.52,1.82],[0,2.28],[-.52,1.82],[-.35,-1.72]],.28,dark,.36);canopy(0,-.5,.64,1.08);for(const side of [-1,1]){engine(side*.7,2.02,.27,.9);lightRail(side*1.78,-.03,2.8,side*-.12);const stabilizer=plate(.08,.82,1.5,side*1.45,.58,.94,dark,side*-.2);stabilizer.rotation.z=side*.3;}const dorsal=plate(.08,.84,1.65,0,.69,.98,shellLight);dorsal.rotation.x=-.08;}
  const hoverGlow=new THREE.Mesh(new THREE.CircleGeometry(1.3,32),new THREE.MeshBasicMaterial({color:accent,transparent:true,opacity:.13,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));hoverGlow.rotation.x=-Math.PI/2;hoverGlow.scale.set(1.45,2.2,1);hoverGlow.position.y=-.08;root.add(hoverGlow);return root;
}

function createPlayerCraft(spec:ShipSpec=SHIPS[0]){const variant=Math.max(0,SHIPS.findIndex(ship=>ship.id===spec.id)),root=createRacer(spec,variant,true);root.name=`${spec.name} cockpit craft`;root.scale.set(.72,.72,.72);root.userData.shipId=spec.id;return root;}

export class FZoneEngine{
  private currentShip:ShipSpec=SHIPS[0];private storyEventIndex=0;private totalLaps=TOTAL_LAPS;
  private renderer:THREE.WebGLRenderer;private scene=new THREE.Scene();private camera=new THREE.PerspectiveCamera(72,1,.05,1400);private clock=new THREE.Clock();private curve=makeTrack();private trackLength=this.curve.getLength();private rig=new THREE.Group();private ship=createPlayerCraft();private keys=new Set<string>();private listeners:Array<()=>void>=[];private audio=new RaceAudio();private snapshot:RaceSnapshot={...INITIAL_SNAPSHOT};private gameMode:GameModeId="story";private distance=0;private previousProgress=0;private lateral=0;private lateralVelocity=0;private headingOffset=0;private speed=0;private boost=100;private boosting=false;private lastBoosting=false;private energyCharging=false;private lap=1;private lapTime=0;private bestLap:number|null=null;private elapsed=0;private lastEmit=0;private hitCooldown=0;private messageTimeout=0;private countdownTime=0;private goTime=0;private countdownLabel:string|null=null;private lastCountdownLabel="";private drafting=false;private drifting=false;private rivals:Rival[]=[];private boostStreaks=new THREE.Group();private boostPads=[.145,.24,.42,.59,.665,.76,.91];private passedPads=new Set<number>();private mapButtonReady=true;private lastAirborne=false;private lastMagnetic=false;private mapCanvas=document.createElement("canvas");private mapTexture=new THREE.CanvasTexture(this.mapCanvas);private mapPanel=new THREE.Mesh(new THREE.PlaneGeometry(.48,.34),new THREE.MeshBasicMaterial({map:this.mapTexture,transparent:true,side:THREE.DoubleSide,depthTest:false,toneMapped:false}));private speedCanvas=document.createElement("canvas");private speedTexture=new THREE.CanvasTexture(this.speedCanvas);private speedPanel=new THREE.Mesh(new THREE.PlaneGeometry(.38,.2),new THREE.MeshBasicMaterial({map:this.speedTexture,transparent:true,side:THREE.DoubleSide,depthTest:false,toneMapped:false}));private countdownCanvas=document.createElement("canvas");private countdownTexture=new THREE.CanvasTexture(this.countdownCanvas);private countdownPanel=new THREE.Mesh(new THREE.PlaneGeometry(.78,.38),new THREE.MeshBasicMaterial({map:this.countdownTexture,transparent:true,depthTest:false,toneMapped:false}));private destroyed=false;
  private vrMenuCanvas=document.createElement("canvas");private vrMenuTexture=new THREE.CanvasTexture(this.vrMenuCanvas);private vrMenuPanel=new THREE.Mesh(new THREE.PlaneGeometry(1.55,1.08),new THREE.MeshBasicMaterial({map:this.vrMenuTexture,transparent:true,side:THREE.DoubleSide,toneMapped:false}));private vrMenuStep:VrMenuStep="mode";private vrMenuIndex=0;private vrMenuActive=false;private vrMenuButtonReady=true;private vrMenuAxisReady=true;
  private vrRaycaster=new THREE.Raycaster();private vrControllers:THREE.Group[]=[];private vrPointerLines:THREE.Line[]=[];private vrPointerCursors:THREE.Mesh[]=[];private vrPointerTargets:Array<number|null>=[null,null];
  constructor(private canvas:HTMLCanvasElement,private emit:(snapshot:RaceSnapshot)=>void){
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:"high-performance"});this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.35;this.renderer.xr.enabled=true;this.renderer.xr.setReferenceSpaceType("local-floor");this.scene.background=new THREE.Color(0x01040a);this.scene.fog=new THREE.FogExp2(0x020913,.0018);
    this.buildWorld();this.bindEvents();this.resize();void this.checkVR();this.emitSnapshot(true);this.renderer.setAnimationLoop(()=>this.loop());
  }
  private buildWorld(){
    this.scene.add(new THREE.HemisphereLight(0x75ecff,0x05050d,1.8));const sun=new THREE.DirectionalLight(0xbfefff,3.2);sun.position.set(60,100,30);this.scene.add(sun);this.scene.add(createTrack(this.curve));this.addRails();this.addEnergyStrips();this.addBoostPads();this.addJumpGates();this.addMagneticTunnels();this.addCity();this.addStars();this.addGate();
    this.rig.add(this.camera);this.camera.position.set(0,1.28,.12);this.rig.add(this.ship);this.ship.position.set(0,.02,.62);this.buildCockpit();this.buildVrMenu();this.buildVrControllers();this.buildBoostStreaks();this.scene.add(this.rig);
    [MAGENTA,AMBER,0x795cff,0x4cff83,0xff5b3d].forEach((color,index)=>{const root=createRacer(SHIPS[index],index);root.scale.setScalar(.82);this.scene.add(root);const lane=(index-2)*3.8;this.rivals.push({root,name:RIVAL_NAMES[index],distance:18+index*14,speed:102+index*3.7,lane,targetLane:lane,decisionTimer:.55+index*.23,color});});this.updateTransforms(0);
  }
  private addRails(){
    const material=new THREE.MeshBasicMaterial({color:CYAN});
    for(const side of [-1,1]){
      let points:THREE.Vector3[]=[];
      const flush=()=>{if(points.length>2)this.scene.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points,false,"centripetal"),Math.max(12,points.length*2),.055,5,false),material));points=[];};
      for(let i=0;i<=SAMPLES;i++){const progress=i/SAMPLES;if(isGap(progress)){flush();continue;}const f=frame(this.curve,progress);points.push(f.center.clone().addScaledVector(f.right,side*(TRACK_WIDTH/2+.12)).addScaledVector(f.up,.34));}
      flush();
    }
    for(let i=0;i<112;i++){const progress=i/112;if(isGap(progress))continue;const f=frame(this.curve,progress),color=i%8===0?AMBER:CYAN;for(const side of [-1,1]){const post=new THREE.Mesh(new THREE.BoxGeometry(.09,.85,.09),new THREE.MeshBasicMaterial({color}));post.position.copy(f.center).addScaledVector(f.right,side*(TRACK_WIDTH/2+.12)).addScaledVector(f.up,.38);post.quaternion.copy(f.quaternion);this.scene.add(post);}}
  }
  private addBoostPads(){this.boostPads.forEach((progress,index)=>{const f=frame(this.curve,progress);for(const lane of [-12,0,12]){const pad=new THREE.Mesh(new THREE.BoxGeometry(3.8,.035,7),new THREE.MeshBasicMaterial({color:index%2?AMBER:CYAN,transparent:true,opacity:.78}));pad.position.copy(f.center).addScaledVector(f.right,lane).addScaledVector(f.up,.03);pad.quaternion.copy(f.quaternion);this.scene.add(pad);}});}
  private addEnergyStrips(){const material=new THREE.MeshBasicMaterial({color:0x4dffb8,transparent:true,opacity:.9,toneMapped:false});for(const [start,end] of ENERGY_RANGES){for(let progress=start;progress<=end;progress+=.004){const f=frame(this.curve,progress);for(const side of [-1,1]){const strip=new THREE.Mesh(new THREE.BoxGeometry(4.4,.045,5.5),material);strip.position.copy(f.center).addScaledVector(f.right,side*(TRACK_WIDTH/2-3)).addScaledVector(f.up,.035);strip.quaternion.copy(f.quaternion);this.scene.add(strip);}}}}
  private addJumpGates(){for(const [start,end] of GAP_RANGES){for(const [progress,color] of [[start-.006,AMBER],[end+.006,CYAN]] as const){const f=frame(this.curve,progress),group=new THREE.Group();group.position.copy(f.center);group.quaternion.copy(f.quaternion);const bar=new THREE.Mesh(new THREE.BoxGeometry(TRACK_WIDTH,.08,.65),new THREE.MeshBasicMaterial({color}));bar.position.y=.04;group.add(bar);for(const side of [-1,1]){const beacon=new THREE.Mesh(new THREE.ConeGeometry(.16,.9,6),new THREE.MeshBasicMaterial({color}));beacon.position.set(side*(TRACK_WIDTH/2-.3),.48,0);group.add(beacon);}this.scene.add(group);}}}
  private addMagneticTunnels(){for(const [start,end] of MAGNETIC_RANGES){const rings=24;for(let i=0;i<=rings;i++){const progress=start+(end-start)*i/rings;if(!tunnelHasClearance(this.curve,progress))continue;const f=frame(this.curve,progress),ring=new THREE.Mesh(new THREE.TorusGeometry(TRACK_WIDTH*.61,.075,5,28),new THREE.MeshBasicMaterial({color:i%4===0?MAGENTA:0x6746a8,transparent:true,opacity:i%4===0?.8:.34}));ring.position.copy(f.center);ring.quaternion.copy(f.quaternion);this.scene.add(ring);}}}
  private addGate(){const f=frame(this.curve,0),group=new THREE.Group(),material=new THREE.MeshBasicMaterial({color:CYAN});group.position.copy(f.center);group.quaternion.copy(f.quaternion);const top=new THREE.Mesh(new THREE.BoxGeometry(TRACK_WIDTH+2,.16,.16),material);top.position.y=4.7;group.add(top);for(const side of [-1,1]){const pillar=new THREE.Mesh(new THREE.BoxGeometry(.16,4.8,.16),material);pillar.position.set(side*(TRACK_WIDTH/2+.9),2.35,0);group.add(pillar);}this.scene.add(group);}
  private addCity(){const towers=new THREE.InstancedMesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial({color:0x07131d,emissive:0x082b38,emissiveIntensity:.45,metalness:.68,roughness:.35}),260),matrix=new THREE.Matrix4(),color=new THREE.Color();for(let i=0;i<260;i++){const angle=i*2.399,radius=95+(i%23)*12,height=8+(i*13%19);matrix.compose(new THREE.Vector3(Math.cos(angle)*radius,height/2-8,Math.sin(angle)*radius),new THREE.Quaternion(),new THREE.Vector3(5+i%5,height,5+(i*3)%7));towers.setMatrixAt(i,matrix);color.setHex(i%9===0?0x114a5d:0x06121b);towers.setColorAt(i,color);}this.scene.add(towers);const floor=new THREE.Mesh(new THREE.CircleGeometry(520,72),new THREE.MeshBasicMaterial({color:0x01040a}));floor.rotation.x=-Math.PI/2;floor.position.y=-8.2;this.scene.add(floor);}
  private addStars(){const positions:number[]=[];for(let i=0;i<900;i++){const radius=180+(i*43%460),angle=i*4.17,y=35+(i*29%230);positions.push(Math.cos(angle)*radius,y,Math.sin(angle)*radius);}const geometry=new THREE.BufferGeometry();geometry.setAttribute("position",new THREE.Float32BufferAttribute(positions,3));this.scene.add(new THREE.Points(geometry,new THREE.PointsMaterial({color:0xbbefff,size:.6,sizeAttenuation:true})));}
  private buildCockpit(){
    const alloy=new THREE.MeshPhysicalMaterial({color:0x071018,metalness:.94,roughness:.17,clearcoat:1,clearcoatRoughness:.12,emissive:0x031b23,emissiveIntensity:.25});
    const inset=new THREE.MeshStandardMaterial({color:0x010408,metalness:.72,roughness:.3});
    const glow=new THREE.MeshBasicMaterial({color:CYAN,toneMapped:false});
    const amber=new THREE.MeshBasicMaterial({color:AMBER,toneMapped:false});
    const center=new THREE.Mesh(new THREE.BoxGeometry(.86,.075,.48),alloy);center.position.set(0,.78,-.62);center.rotation.x=-.16;this.rig.add(center);
    const centerScreen=new THREE.Mesh(new THREE.PlaneGeometry(.46,.16),new THREE.MeshBasicMaterial({color:0x0d6270,transparent:true,opacity:.72,toneMapped:false}));centerScreen.position.set(0,.846,-.76);centerScreen.rotation.x=-1.42;this.rig.add(centerScreen);
    for(const side of [-1,1]){
      const consoleMesh=new THREE.Mesh(new THREE.BoxGeometry(.68,.07,.82),alloy);consoleMesh.position.set(side*.72,.72,-.38);consoleMesh.rotation.set(-.14,side*-.1,side*-.025);this.rig.add(consoleMesh);
      const consoleInset=new THREE.Mesh(new THREE.BoxGeometry(.48,.018,.45),inset);consoleInset.position.set(side*.72,.77,-.53);consoleInset.rotation.copy(consoleMesh.rotation);this.rig.add(consoleInset);
      for(let light=0;light<4;light++){const indicator=new THREE.Mesh(new THREE.BoxGeometry(.065,.014,.16),light===3?amber:glow);indicator.position.set(side*(.53+light*.105),.79,-.55+light*.035);indicator.rotation.copy(consoleMesh.rotation);this.rig.add(indicator);}
      const strut=new THREE.Mesh(new THREE.CapsuleGeometry(.035,1.55,5,10),alloy);strut.position.set(side*.82,1.26,-.88);strut.rotation.x=-.58;strut.rotation.z=side*-.22;this.rig.add(strut);
      const strutLight=new THREE.Mesh(new THREE.CapsuleGeometry(.009,1.42,4,8),glow);strutLight.position.copy(strut.position);strutLight.rotation.copy(strut.rotation);strutLight.position.x-=side*.038;this.rig.add(strutLight);
    }
    const brow=new THREE.Mesh(new THREE.TorusGeometry(1.03,.035,8,40,Math.PI),alloy);brow.position.set(0,1.14,-.92);brow.rotation.z=Math.PI;this.rig.add(brow);
    const reticle=new THREE.Mesh(new THREE.RingGeometry(.055,.064,24),new THREE.MeshBasicMaterial({color:CYAN,transparent:true,opacity:.75,side:THREE.DoubleSide,toneMapped:false}));reticle.position.set(0,1.48,-2.15);this.rig.add(reticle);
    this.mapCanvas.width=512;this.mapCanvas.height=360;this.mapPanel.position.set(.61,.91,-.8);this.mapPanel.rotation.set(-.34,-.08,0);this.mapPanel.renderOrder=22;this.mapPanel.visible=false;this.rig.add(this.mapPanel);this.drawCockpitMap(0);
    this.speedCanvas.width=512;this.speedCanvas.height=256;this.speedPanel.position.set(-.56,.86,-.67);this.speedPanel.rotation.set(-.42,.1,0);this.speedPanel.renderOrder=22;this.speedPanel.visible=false;this.rig.add(this.speedPanel);this.drawSpeedPanel(0,100,false);
    this.countdownCanvas.width=512;this.countdownCanvas.height=256;this.countdownPanel.position.set(0,1.58,-2.35);this.countdownPanel.renderOrder=20;this.countdownPanel.visible=false;this.rig.add(this.countdownPanel);this.drawCountdownPanel(null);
  }
  private buildVrMenu(){this.vrMenuCanvas.width=1024;this.vrMenuCanvas.height=720;this.vrMenuPanel.position.set(0,1.5,-2.25);this.vrMenuPanel.renderOrder=24;this.vrMenuPanel.visible=false;this.rig.add(this.vrMenuPanel);this.drawVrMenu();}
  private buildVrControllers(){for(let index=0;index<2;index++){const color=index===0?CYAN:MAGENTA,controller=this.renderer.xr.getController(index),lineGeometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,0,-1)]),line=new THREE.Line(lineGeometry,new THREE.LineBasicMaterial({color,transparent:true,opacity:.9,depthTest:false,toneMapped:false})),cursor=new THREE.Mesh(new THREE.RingGeometry(.018,.032,24),new THREE.MeshBasicMaterial({color,side:THREE.DoubleSide,depthTest:false,toneMapped:false})),handle=new THREE.Mesh(new THREE.CylinderGeometry(.025,.035,.13,12),new THREE.MeshStandardMaterial({color:0x102a34,emissive:color,emissiveIntensity:.5,metalness:.75,roughness:.25}));line.scale.z=4;line.renderOrder=28;line.visible=false;cursor.renderOrder=29;cursor.visible=false;handle.rotation.x=Math.PI/2;handle.position.z=.055;controller.add(line,handle);const onSelect=()=>this.selectVrPointer(index);controller.addEventListener("selectstart",onSelect);this.listeners.push(()=>controller.removeEventListener("selectstart",onSelect));this.rig.add(controller);this.scene.add(cursor);this.vrControllers.push(controller);this.vrPointerLines.push(line);this.vrPointerCursors.push(cursor);}}
  private buildBoostStreaks(){
    const geometry=new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,0,0),new THREE.Vector3(0,0,-2.8)]);
    for(let index=0;index<24;index++){const angle=index/24*Math.PI*2,radius=.75+(index%4)*.16,line=new THREE.Line(geometry,new THREE.LineBasicMaterial({color:index%5===0?AMBER:CYAN,transparent:true,opacity:index%3===0?.7:.38,depthTest:false,toneMapped:false}));line.position.set(Math.cos(angle)*radius,Math.sin(angle)*radius,-2.4-(index%7)*1.15);line.scale.z=.7+(index%5)*.18;line.renderOrder=18;this.boostStreaks.add(line);}
    this.boostStreaks.visible=false;this.camera.add(this.boostStreaks);
  }
  private bindEvents(){this.addEvent(window,"resize",()=>this.resize());this.addEvent(window,"keydown",event=>{this.keys.add(event.code);if(event.code==="Escape")this.togglePause();if(event.code==="KeyM"&&!event.repeat)this.toggleMinimap();});this.addEvent(window,"keyup",event=>this.keys.delete(event.code));this.renderer.xr.addEventListener("sessionstart",()=>{this.snapshot.vrActive=true;this.snapshot.inputMode="vr";const racing=this.snapshot.phase==="racing"||this.snapshot.phase==="countdown";this.mapPanel.visible=racing&&this.snapshot.minimapVisible;this.speedPanel.visible=racing;this.vrMenuPanel.visible=this.vrMenuActive;this.renderer.setPixelRatio(1);this.renderer.xr.setFoveation(.65);this.emitSnapshot(true);});this.renderer.xr.addEventListener("sessionend",()=>{this.snapshot.vrActive=false;this.vrMenuActive=false;this.vrMenuPanel.visible=false;this.hideVrPointers();this.mapPanel.visible=false;this.speedPanel.visible=false;this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));this.resize();this.emitSnapshot(true);});}
  private addEvent<K extends keyof WindowEventMap>(target:Window,type:K,fn:(event:WindowEventMap[K])=>void){target.addEventListener(type,fn);this.listeners.push(()=>target.removeEventListener(type,fn));}
  private async checkVR(){const xr=navigator.xr;this.snapshot.vrApiAvailable=Boolean(xr);this.snapshot.vrChecked=true;this.emitSnapshot(true);if(!xr)return;try{this.snapshot.vrSupported=await xr.isSessionSupported("immersive-vr");}catch{this.snapshot.vrSupported=false;}this.emitSnapshot(true);}
  setAudioSettings(settings:AudioSettings){this.audio.setSettings(settings);}
  configureRace(mode:GameModeId,shipId=SHIPS[0].id,storyEventIndex=0){this.gameMode=mode;this.currentShip=SHIPS.find(ship=>ship.id===shipId)??SHIPS[0];if(this.ship.userData.shipId!==this.currentShip.id)this.replacePlayerCraft();this.storyEventIndex=clamp(Math.round(storyEventIndex),0,STORY_EVENTS.length-1);const event=STORY_EVENTS[this.storyEventIndex],support=RIVAL_NAMES.filter(name=>name!==event.rival);this.totalLaps=mode==="story"?event.laps:TOTAL_LAPS;this.rivals.forEach((rival,index)=>{rival.root.visible=mode!=="arcade";rival.name=mode==="story"?(index===this.rivals.length-1?event.rival:support[index]):RIVAL_NAMES[index];});this.emitSnapshot(true);}
  private replacePlayerCraft(){const previous=this.ship,next=createPlayerCraft(this.currentShip);next.position.set(0,.02,.62);next.rotation.copy(previous.rotation);this.rig.remove(previous);previous.traverse(object=>{if(!(object instanceof THREE.Mesh))return;object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>material.dispose());});this.ship=next;this.rig.add(this.ship);}
  returnToMenu(){this.snapshot.phase="menu";this.speed=0;this.boosting=false;this.lastBoosting=false;this.energyCharging=false;this.countdownPanel.visible=false;this.audio.update(0,0,false,false);if(this.renderer.xr.isPresenting){this.openVrMenu("mode");}this.emitSnapshot(true);}
  private async requestVrSession(){if(!globalThis.isSecureContext)throw new Error("O modo VR exige uma página HTTPS segura");if(!navigator.xr)throw new Error("A API WebXR não apareceu. Abra no Meta Quest Browser e recarregue a página");const session=await navigator.xr.requestSession("immersive-vr",{optionalFeatures:["local-floor","bounded-floor","hand-tracking"]});await this.renderer.xr.setSession(session);}
  async enterVRLobby(){void this.audio.start();this.snapshot.phase="menu";this.vrMenuActive=true;this.vrMenuStep="mode";this.vrMenuIndex=0;this.drawVrMenu();try{await this.requestVrSession();this.vrMenuPanel.visible=true;this.speedPanel.visible=false;this.mapPanel.visible=false;this.emitSnapshot(true);}catch(error){this.vrMenuActive=false;throw error;}}
  async enterVR(){void this.audio.start();const shouldStart=this.snapshot.phase==="menu"||this.snapshot.phase==="finished";await this.requestVrSession();if(shouldStart)this.start();}
  start(){void this.audio.start();if(this.snapshot.phase==="paused"){this.snapshot.phase="racing";this.clock.getDelta();this.emitSnapshot(true);return;}this.vrMenuActive=false;this.vrMenuPanel.visible=false;this.speedPanel.visible=this.renderer.xr.isPresenting;this.mapPanel.visible=this.renderer.xr.isPresenting&&this.snapshot.minimapVisible;this.distance=0;this.previousProgress=0;this.lateral=0;this.lateralVelocity=0;this.headingOffset=0;this.speed=0;this.boost=100;this.boosting=false;this.lastBoosting=false;this.energyCharging=false;this.lap=1;this.lapTime=0;this.bestLap=null;this.elapsed=0;this.drafting=false;this.drifting=false;this.countdownTime=3.05;this.goTime=0;this.countdownLabel="3";this.lastCountdownLabel="3";this.passedPads.clear();const storyDifficulty=this.gameMode==="story"?this.storyEventIndex*2.25:0;this.rivals.forEach((rival,index)=>{const lane=(index-2)*6;rival.distance=18+index*15;rival.speed=(this.gameMode==="cup"?118:114)+index*4.2+storyDifficulty;rival.lane=lane;rival.targetLane=lane;rival.decisionTimer=.55+index*.23;});this.snapshot.phase="countdown";this.drawCountdownPanel("3");this.countdownPanel.visible=true;this.pulse(.18,45);this.emitSnapshot(true);this.clock.getDelta();}
  toggleMinimap(){this.snapshot.minimapVisible=!this.snapshot.minimapVisible;this.mapPanel.visible=this.snapshot.vrActive&&this.snapshot.minimapVisible;if(this.mapPanel.visible)this.drawCockpitMap((this.distance/this.trackLength)%1);this.emitSnapshot(true);}
  private togglePause(){if(this.snapshot.phase==="racing"){this.snapshot.phase="paused";this.boosting=false;this.lastBoosting=false;}else if(this.snapshot.phase==="paused")this.snapshot.phase="racing";this.audio.update(this.speed,0,false,this.snapshot.phase==="racing");this.emitSnapshot(true);}
  private readControls():ControlState{let steer=(this.keys.has("KeyD")||this.keys.has("ArrowRight")?1:0)-(this.keys.has("KeyA")||this.keys.has("ArrowLeft")?1:0),throttle=this.keys.has("KeyW")||this.keys.has("ArrowUp")?1:0,brake=this.keys.has("KeyS")||this.keys.has("ArrowDown")?1:0,boost=this.keys.has("ShiftLeft")||this.keys.has("ShiftRight")||this.keys.has("Space"),map=false,mode:InputMode="keyboard";const sources=Array.from(this.renderer.xr.getSession()?.inputSources??[]);if(sources.length){const left=sources.find(source=>source.handedness==="left")?.gamepad,right=sources.find(source=>source.handedness==="right")?.gamepad,axes=left?.axes??[];steer=deadzone(axes.length>=4?axes[2]??0:axes[0]??0);throttle=right?.buttons[0]?.value??0;brake=left?.buttons[0]?.value??0;boost=Boolean(right?.buttons[1]?.pressed||right?.buttons[4]?.pressed);map=Boolean(left?.buttons[4]?.pressed||left?.buttons[5]?.pressed);mode="vr";}else{const pad=Array.from(navigator.getGamepads()).find(Boolean);if(pad){steer=deadzone(pad.axes[0]??0);throttle=Math.max(throttle,pad.buttons[7]?.value??0);brake=Math.max(brake,pad.buttons[6]?.value??0);boost||=Boolean(pad.buttons[0]?.pressed||pad.buttons[5]?.pressed);map=Boolean(pad.buttons[3]?.pressed||pad.buttons[8]?.pressed);mode="gamepad";}}return{steer,throttle,brake,boost,map,mode};}
  private loop(){if(this.destroyed)return;const dt=Math.min(this.clock.getDelta(),.05);if(this.snapshot.phase==="countdown")this.updateCountdown(dt);else if(this.snapshot.phase==="racing")this.updateRace(dt);else{this.audio.update(0,0,false,false);if(this.renderer.xr.isPresenting&&this.vrMenuActive){this.updateVrPointers();this.updateVrMenu();}this.updateTransforms(dt);}this.renderer.render(this.scene,this.camera);}
  private updateCountdown(dt:number){this.audio.update(0,0,false,true);this.countdownTime=Math.max(0,this.countdownTime-dt);const label=this.countdownTime>2?"3":this.countdownTime>1?"2":this.countdownTime>0?"1":"GO";if(label!==this.lastCountdownLabel){this.lastCountdownLabel=label;this.countdownLabel=label;this.drawCountdownPanel(label);this.pulse(label==="GO"?.42:.2,label==="GO"?90:45);this.emitSnapshot(true);}if(this.countdownTime<=0){this.snapshot.phase="racing";this.goTime=.8;this.showMessage("Propulsores liberados");this.emitSnapshot(true);}this.updateTransforms(dt);}
  private updateRace(dt:number){
    const controls=this.readControls();this.snapshot.inputMode=controls.mode;
    if(this.goTime>0){this.goTime-=dt;if(this.goTime<=0){this.countdownLabel=null;this.countdownPanel.visible=false;this.emitSnapshot(true);}}
    if(controls.map&&this.mapButtonReady){this.toggleMinimap();this.mapButtonReady=false;}else if(!controls.map)this.mapButtonReady=true;
    this.boosting=controls.boost&&this.boost>1&&this.speed>24;
    if(this.boosting&&!this.lastBoosting){this.audio.boostHit();this.showMessage("Nitro acionado");this.pulse(.24,55);}this.lastBoosting=this.boosting;
    const acceleration=.82+this.currentShip.stats.acceleration*.07,topSpeed=104+this.currentShip.stats.topSpeed*5.5,boostPower=.75+this.currentShip.stats.boost*.08;this.speed=advanceSpeed(this.speed,controls.throttle,controls.brake,this.boosting,dt,{topSpeed,acceleration,boostPower});if(controls.throttle<.03&&controls.brake<.03&&!this.boosting&&this.speed<.75)this.speed=0;this.audio.update(this.speed,controls.throttle,this.boosting,true);
    const projectedProgress=((this.distance+this.speed*dt)/this.trackLength)%1,airborne=isGap(projectedProgress),magnetic=Math.abs(magneticBank(projectedProgress))>.1;
    const handling=.78+this.currentShip.stats.handling*.09,grip=airborne?.55:magnetic?6.2:controls.brake>.12?.9:2.35,steeringPower=(38+this.speed*.2)*handling*(airborne?.42:1),lateralCap=(24+this.currentShip.stats.handling*2)*(controls.brake>.12?1.12:1);
    this.lateralVelocity+=controls.steer*steeringPower*dt;this.lateralVelocity*=Math.exp(-grip*dt);this.lateralVelocity=clamp(this.lateralVelocity,-lateralCap,lateralCap);this.lateral+=this.lateralVelocity*dt;
    this.drifting=!airborne&&controls.brake>.12&&Math.abs(controls.steer)>.28&&this.speed>46;
    const targetHeading=clamp(-controls.steer*.075-this.lateralVelocity*.012,-.22,.22);this.headingOffset+=(targetHeading-this.headingOffset)*Math.min(1,dt*5.5);this.ship.rotation.y+=(this.headingOffset-this.ship.rotation.y)*Math.min(1,dt*7);this.ship.rotation.z+=(-controls.steer*.13-this.ship.rotation.z)*Math.min(1,dt*6);
    this.distance+=this.speed*dt;const progress=(this.distance/this.trackLength)%1,edge=TRACK_WIDTH/2-1.65;this.energyCharging=!airborne&&isEnergyZone(progress)&&Math.abs(this.lateral)>TRACK_WIDTH/2-5.5;this.boost=clamp(this.boost+(this.boosting?-29:this.energyCharging?18:.18)*dt,0,100);if(this.energyCharging&&this.boost<99&&this.messageTimeout<=0)this.showMessage("Recarga lateral ativa");
    if(!airborne&&Math.abs(this.lateral)>edge){const side=Math.sign(this.lateral)||1;this.lateral=side*edge;this.lateralVelocity=-side*Math.max(4,Math.abs(this.lateralVelocity)*.42);if(this.hitCooldown<=0){this.speed*=.78;this.snapshot.impactPulse+=1;this.hitCooldown=.42;this.showMessage("Rebote na barreira");this.pulse(.38,78);}}
    if(airborne&&!this.lastAirborne){this.speed=Math.max(this.speed,88);this.showMessage("Salto orbital");this.pulse(.28,65);}
    if(magnetic&&!this.lastMagnetic){this.showMessage("Aderência magnética");this.pulse(.18,45);}
    this.lastAirborne=airborne;this.lastMagnetic=magnetic;this.hitCooldown-=dt;this.lapTime+=dt;this.elapsed+=dt;
    if(progress<this.previousProgress&&this.speed>10){this.bestLap=this.bestLap===null?this.lapTime:Math.min(this.bestLap,this.lapTime);this.lap+=1;this.lapTime=0;this.passedPads.clear();if(this.lap>this.totalLaps){this.lap=this.totalLaps;this.snapshot.phase="finished";this.boosting=false;this.lastBoosting=false;this.audio.update(this.speed,0,false,false);this.speed*=.7;this.showMessage("Prova concluída");if(this.renderer.xr.isPresenting)this.openVrMenu("results");}else this.showMessage(`Volta ${this.lap}`);}
    this.previousProgress=progress;this.checkPads(progress);this.updateRivals(dt,controls.throttle);this.resolveRivalCollisions();this.updateTransforms(dt);
    if(this.messageTimeout>0){this.messageTimeout-=dt;if(this.messageTimeout<=0)this.snapshot.message="";}
    if(this.elapsed-this.lastEmit>.05){this.lastEmit=this.elapsed;this.emitSnapshot();}
  }
  private activeRivals(){return this.gameMode==="arcade"?[]:this.rivals;}
  private updateRivals(dt:number,throttle:number){
    const laneLimit=TRACK_WIDTH/2-2.3,active=this.activeRivals();
    active.forEach((rival,index)=>{
      rival.distance+=(rival.speed+Math.sin(this.elapsed*.7+index)*5)*dt;rival.decisionTimer-=dt;
      if(rival.decisionTimer<=0){rival.decisionTimer=.75+(index%3)*.24;const aheadOfPlayer=signedTrackDelta(rival.distance,this.distance,this.trackLength);if(aheadOfPlayer>5&&aheadOfPlayer<30&&index%2===0)rival.targetLane=clamp(this.lateral+(index%4===0?-1.4:1.4),-laneLimit,laneLimit);else rival.targetLane=clamp(Math.sin(this.elapsed*.42+index*1.73)*laneLimit*.82,-laneLimit,laneLimit);}
      for(const other of active){if(other===rival)continue;const delta=signedTrackDelta(other.distance,rival.distance,this.trackLength);if(delta>0&&delta<10&&Math.abs(other.lane-rival.lane)<3.2)rival.targetLane=clamp(rival.lane+(index%2===0?-4.2:4.2),-laneLimit,laneLimit);}
      const laneStep=(3.4+rival.speed*.018)*dt;rival.lane+=clamp(rival.targetLane-rival.lane,-laneStep,laneStep);
    });
    this.drafting=false;if(this.speed>32&&throttle>.15)for(const rival of active){const ahead=signedTrackDelta(rival.distance,this.distance,this.trackLength);if(ahead>5&&ahead<30&&Math.abs(rival.lane-this.lateral)<2.8){this.drafting=true;break;}}
    if(this.drafting)this.speed=Math.min(164,this.speed+11*dt);
  }
  private resolveRivalCollisions(){
    if(this.hitCooldown>0)return;
    const active=this.activeRivals();for(let index=0;index<active.length;index++){const rival=active[index],longitudinal=signedTrackDelta(rival.distance,this.distance,this.trackLength),lateralGap=this.lateral-rival.lane;if(Math.abs(longitudinal)>4.5||Math.abs(lateralGap)>2.65)continue;const side=Math.abs(lateralGap)>.15?Math.sign(lateralGap):(index%2===0?-1:1);this.lateralVelocity+=side*(7.5+Math.min(5,this.speed*.025));rival.lane=clamp(rival.lane-side*1.15,-TRACK_WIDTH/2+2.3,TRACK_WIDTH/2-2.3);rival.targetLane=rival.lane;this.speed*=longitudinal>0?.82:.9;rival.speed=Math.max(82,rival.speed*(longitudinal>0?1.025:.96));this.snapshot.impactPulse+=1;this.hitCooldown=.48;this.showMessage(longitudinal>0?"Choque frontal":"Contato lateral");this.pulse(.46,95);break;}
  }
  private checkPads(progress:number){this.boostPads.forEach((pad,index)=>{const distance=Math.min(Math.abs(progress-pad),1-Math.abs(progress-pad));if(distance<.008&&!this.passedPads.has(index)){this.passedPads.add(index);this.speed=Math.min(154,this.speed+14);this.showMessage("Placa de impulso");this.pulse(.22,45);}});}
  private updateTransforms(dt:number){const progress=(this.distance/this.trackLength)%1,f=frame(this.curve,progress),lift=gapLift(progress);this.rig.position.copy(f.center).addScaledVector(f.right,this.lateral).addScaledVector(f.up,.35+lift);this.rig.quaternion.slerp(f.quaternion,dt>0?Math.min(1,dt*6):1);this.camera.position.x+=(clamp(-this.lateralVelocity*.009,-.09,.09)-this.camera.position.x)*Math.min(1,dt*3.5);this.rivals.forEach((rival,index)=>{const rivalProgress=(rival.distance/this.trackLength)%1,rf=frame(this.curve,rivalProgress);rival.root.position.copy(rf.center).addScaledVector(rf.right,rival.lane).addScaledVector(rf.up,.48+gapLift(rivalProgress));rival.root.quaternion.copy(rf.quaternion);rival.root.rotation.y=clamp((rival.targetLane-rival.lane)*-.035,-.16,.16);rival.root.rotation.z=Math.sin(this.elapsed*.8+index)*.035;});this.boostStreaks.visible=this.boosting;this.boostStreaks.children.forEach((streak,index)=>{streak.position.z+=dt*(18+this.speed*.13);if(streak.position.z>-.8)streak.position.z=-9-(index%7)*1.15;});if(!this.renderer.xr.isPresenting){const targetFov=this.boosting?80:72;this.camera.fov+=(targetFov-this.camera.fov)*Math.min(1,dt*7);this.camera.updateProjectionMatrix();}if(this.mapPanel.visible)this.drawCockpitMap(progress);}
  private position(){return 1+this.activeRivals().filter(rival=>rival.distance>this.distance).length;}
  private showMessage(message:string){this.snapshot.message=message;this.snapshot.messagePulse+=1;this.messageTimeout=1.35;}
  private pulse(intensity:number,duration:number){for(const source of Array.from(this.renderer.xr.getSession()?.inputSources??[])){const actuator=source.gamepad?.hapticActuators?.[0];if(actuator)void actuator.pulse(intensity,duration);}}
  private openVrMenu(step:VrMenuStep){this.vrMenuActive=true;this.vrMenuStep=step;this.vrMenuIndex=0;this.vrMenuButtonReady=false;this.vrMenuAxisReady=false;this.vrMenuPanel.visible=true;this.speedPanel.visible=false;this.mapPanel.visible=false;this.countdownPanel.visible=false;this.drawVrMenu();}
  private hideVrPointers(){this.vrPointerLines.forEach(line=>line.visible=false);this.vrPointerCursors.forEach(cursor=>cursor.visible=false);this.vrPointerTargets=[null,null];}
  private vrMenuIndexFromUv(uv:THREE.Vector2){const choices=this.vrMenuChoices(),x=uv.x*1024,y=(1-uv.y)*720,cardWidth=Math.min(820,choices.length<=3?760:700),cardHeight=choices.length>4?70:84,startY=250;if(x<64||x>64+cardWidth)return null;for(let index=0;index<choices.length;index++){const top=startY+index*(cardHeight+14);if(y>=top&&y<=top+cardHeight)return index;}return null;}
  private updateVrPointers(){this.scene.updateMatrixWorld(true);const panelQuaternion=this.vrMenuPanel.getWorldQuaternion(new THREE.Quaternion());this.vrControllers.forEach((controller,index)=>{const line=this.vrPointerLines[index],cursor=this.vrPointerCursors[index];line.visible=true;this.vrRaycaster.setFromXRController(controller);const hit=this.vrRaycaster.intersectObject(this.vrMenuPanel,false)[0];if(!hit){line.scale.z=4;cursor.visible=false;this.vrPointerTargets[index]=null;return;}line.scale.z=Math.max(.1,hit.distance);cursor.visible=true;cursor.position.copy(hit.point);cursor.quaternion.copy(panelQuaternion);const target=hit.uv?this.vrMenuIndexFromUv(hit.uv):null;this.vrPointerTargets[index]=target;if(target!==null&&target!==this.vrMenuIndex){this.vrMenuIndex=target;this.drawVrMenu();this.pulse(.08,18);}});}
  private selectVrPointer(controllerIndex:number){if(!this.vrMenuActive)return;const target=this.vrPointerTargets[controllerIndex];if(target===null||target===undefined)return;this.vrMenuIndex=target;this.drawVrMenu();this.pulse(.18,35);this.confirmVrMenu();}
  private vrMenuChoices(){if(this.vrMenuStep==="mode")return GAME_MODES.map(mode=>mode.name);if(this.vrMenuStep==="ship")return SHIPS.map(ship=>ship.name);if(this.vrMenuStep==="track")return TRACKS.filter(track=>track.available).map(track=>track.name);const canAdvance=this.gameMode==="story"&&this.position()<=3&&this.storyEventIndex<STORY_EVENTS.length-1;return [canAdvance?"Próxima corrida":"Correr novamente","Menu principal","Sair do VR"];}
  private updateVrMenu(){const sources=Array.from(this.renderer.xr.getSession()?.inputSources??[]),left=sources.find(source=>source.handedness==="left")?.gamepad,right=sources.find(source=>source.handedness==="right")?.gamepad,axes=left?.axes??[],axis=axes.length>=4?axes[2]??0:axes[0]??0,confirm=Boolean(right?.buttons[4]?.pressed),back=Boolean(left?.buttons[5]?.pressed||right?.buttons[5]?.pressed),choices=this.vrMenuChoices();if(Math.abs(axis)<.3)this.vrMenuAxisReady=true;if(Math.abs(axis)>.65&&this.vrMenuAxisReady){this.vrMenuIndex=(this.vrMenuIndex+(axis>0?1:-1)+choices.length)%choices.length;this.vrMenuAxisReady=false;this.drawVrMenu();this.pulse(.12,24);}if(!confirm&&!back)this.vrMenuButtonReady=true;if(this.vrMenuButtonReady&&(confirm||back)){this.vrMenuButtonReady=false;if(back){if(this.vrMenuStep==="ship")this.openVrMenu("mode");else if(this.vrMenuStep==="track")this.openVrMenu("ship");return;}this.confirmVrMenu();}}
  private confirmVrMenu(){if(this.vrMenuStep==="mode"){this.gameMode=GAME_MODES[this.vrMenuIndex]?.id??"story";if(this.gameMode==="story")this.storyEventIndex=0;this.openVrMenu("ship");return;}if(this.vrMenuStep==="ship"){this.currentShip=SHIPS[this.vrMenuIndex]??SHIPS[0];this.openVrMenu("track");return;}if(this.vrMenuStep==="track"){this.hideVrPointers();this.configureRace(this.gameMode,this.currentShip.id,this.storyEventIndex);this.start();return;}const canAdvance=this.gameMode==="story"&&this.position()<=3&&this.storyEventIndex<STORY_EVENTS.length-1;if(this.vrMenuIndex===0){this.hideVrPointers();if(canAdvance)this.storyEventIndex+=1;this.configureRace(this.gameMode,this.currentShip.id,this.storyEventIndex);this.start();}else if(this.vrMenuIndex===1){this.snapshot.phase="menu";this.openVrMenu("mode");this.emitSnapshot(true);}else void this.renderer.xr.getSession()?.end();}
  private drawVrMenu(){const context=this.vrMenuCanvas.getContext("2d");if(!context)return;const choices=this.vrMenuChoices(),event=STORY_EVENTS[this.storyEventIndex],titles={mode:"Escolha o modo",ship:"Escolha sua nave",track:"Escolha o circuito",results:this.position()<=3?"Pódio confirmado":"Prova concluída"},subtitles={mode:"Analógico esquerdo para navegar · gatilho direito para confirmar",ship:`${GAME_MODES.find(mode=>mode.id===this.gameMode)?.name??"F-Zone"} · cada nave altera a pilotagem`,track:this.gameMode==="story"?`Evento ${event.chapter} · Rival ${event.rival}`:"Selecione a pista e prepare a largada",results:`Posição ${this.position()}/${this.activeRivals().length+1} · ${this.gameMode==="story"?event.title:"Resultado oficial"}`};context.clearRect(0,0,1024,720);context.fillStyle="rgba(1,8,14,.96)";context.beginPath();context.roundRect(18,18,988,684,34);context.fill();context.strokeStyle="#69f6ff";context.lineWidth=4;context.stroke();context.fillStyle="#69f6ff";context.font="700 24px monospace";context.letterSpacing="8px";context.fillText("F-ZONE VR · ESPAÇO IMERSIVO",64,82);context.letterSpacing="0px";context.fillStyle="#effdff";context.font="800 58px sans-serif";context.fillText(titles[this.vrMenuStep],64,160);context.fillStyle="#8ba5ad";context.font="24px sans-serif";context.fillText(subtitles[this.vrMenuStep],64,205);const cardWidth=Math.min(820,choices.length<=3?760:700),cardHeight=choices.length>4?70:84,startY=250;choices.forEach((choice,index)=>{const selected=index===this.vrMenuIndex,y=startY+index*(cardHeight+14);context.fillStyle=selected?"rgba(105,246,255,.18)":"rgba(12,32,42,.78)";context.fillRect(64,y,cardWidth,cardHeight);context.strokeStyle=selected?"#69f6ff":"rgba(105,246,255,.2)";context.lineWidth=selected?4:2;context.strokeRect(64,y,cardWidth,cardHeight);context.fillStyle=selected?"#ffffff":"#90aab2";context.font=`${selected?"800":"600"} ${choices.length>4?28:32}px sans-serif`;context.fillText(`${selected?"›":" "} ${choice}`,90,y+cardHeight*.64);});context.fillStyle="#ffc25e";context.font="700 20px monospace";context.fillText("GATILHO: CONFIRMAR   ·   B: VOLTAR",64,676);this.vrMenuTexture.needsUpdate=true;}
  private emitSnapshot(force=false){if(this.destroyed&&!force)return;const progress=(this.distance/this.trackLength)%1,active=this.activeRivals(),opponents=active.map(rival=>({name:rival.name,progress:((rival.distance/this.trackLength)%1+1)%1,lane:rival.lane,place:1+[this.distance,...active.filter(other=>other!==rival).map(other=>other.distance)].filter(distance=>distance>rival.distance).length,color:`#${rival.color.toString(16).padStart(6,"0")}`,delta:signedTrackDelta(rival.distance,this.distance,this.trackLength)})).sort((a,b)=>a.place-b.place),physicalTop=104+this.currentShip.stats.topSpeed*5.5,cruiseCap=400+this.currentShip.stats.topSpeed*30,boostCap=Math.min(600,cruiseCap+40+this.currentShip.stats.boost*4),displaySpeed=this.speed<.75?0:Math.min(this.boosting?boostCap:cruiseCap,Math.round(this.speed/physicalTop*cruiseCap));this.snapshot={...this.snapshot,speed:this.speed,displaySpeed,boost:this.boost,boosting:this.boosting,energyCharging:this.energyCharging,lap:this.lap,totalLaps:this.totalLaps,lapTime:this.lapTime,bestLap:this.bestLap,position:this.position(),racers:active.length+1,opponents,progress,sector:trackSector(progress),airborne:isGap(progress),magnetic:Math.abs(magneticBank(progress))>.1,drafting:this.drafting,drifting:this.drifting,countdown:this.countdownLabel};this.drawSpeedPanel(displaySpeed,this.boost,this.energyCharging);this.emit({...this.snapshot});}
  private drawSpeedPanel(speed:number,energy:number,charging:boolean){const context=this.speedCanvas.getContext("2d");if(!context)return;context.clearRect(0,0,512,256);context.fillStyle="rgba(1,8,14,.88)";context.beginPath();context.roundRect(12,12,488,232,26);context.fill();context.strokeStyle=charging?"#4dffb8":"rgba(105,246,255,.65)";context.lineWidth=4;context.stroke();context.fillStyle="#dffeff";context.font="900 108px monospace";context.textAlign="right";context.fillText(String(speed),356,132);context.textAlign="left";context.font="700 25px monospace";context.fillStyle="#69f6ff";context.fillText("KM/H",370,124);context.fillStyle="rgba(105,246,255,.16)";context.fillRect(42,174,428,28);context.fillStyle=energy<24?"#ff3e93":charging?"#4dffb8":"#69f6ff";context.fillRect(42,174,428*energy/100,28);context.font="700 20px monospace";context.fillStyle="#dffeff";context.fillText(charging?`RECARGA ${Math.round(energy)}%`:`NITRO ${Math.round(energy)}%`,42,229);this.speedTexture.needsUpdate=true;}
  private drawCountdownPanel(label:string|null){const context=this.countdownCanvas.getContext("2d");if(!context)return;const colors=["#ff365c","#ffc25e","#51ff9f"],active=label==="3"?0:label==="2"||label==="1"?1:label==="GO"?2:-1;context.clearRect(0,0,512,256);context.fillStyle="rgba(1,8,14,.86)";context.beginPath();context.roundRect(36,24,440,208,28);context.fill();context.strokeStyle="rgba(105,246,255,.45)";context.lineWidth=3;context.stroke();colors.forEach((color,index)=>{context.fillStyle=index===active?color:"#14232b";context.shadowColor=index===active?color:"transparent";context.shadowBlur=index===active?28:0;context.beginPath();context.arc(154+index*102,80,27,0,Math.PI*2);context.fill();context.shadowBlur=0;});if(label){context.textAlign="center";context.font="900 92px sans-serif";context.fillStyle=label==="3"?colors[0]:label==="GO"?colors[2]:colors[1];context.shadowColor=context.fillStyle;context.shadowBlur=24;context.fillText(label,256,205);context.shadowBlur=0;}this.countdownTexture.needsUpdate=true;this.countdownPanel.visible=label!==null;}
  private drawCockpitMap(progress:number){const context=this.mapCanvas.getContext("2d");if(!context)return;const width=this.mapCanvas.width,height=this.mapCanvas.height,project=(point:THREE.Vector3)=>({x:28+(point.x+250)/530*(width-56),y:24+(210-point.z)/385*(height-48)}),mapPoint=(p:number,lane=0)=>{const f=frame(this.curve,p);return project(f.center.clone().addScaledVector(f.right,lane));};context.clearRect(0,0,width,height);context.fillStyle="rgba(2,12,20,.88)";context.fillRect(0,0,width,height);context.strokeStyle="rgba(105,246,255,.18)";context.lineWidth=1;for(let x=0;x<width;x+=32){context.beginPath();context.moveTo(x,0);context.lineTo(x,height);context.stroke();}for(let y=0;y<height;y+=32){context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke();}context.lineWidth=7;context.lineCap="round";context.strokeStyle="#69f6ff";let drawing=false;for(let i=0;i<=220;i++){const p=i/220;if(isGap(p)){if(drawing)context.stroke();drawing=false;continue;}const point=project(this.curve.getPointAt(p));if(!drawing){context.beginPath();context.moveTo(point.x,point.y);drawing=true;}else context.lineTo(point.x,point.y);}if(drawing)context.stroke();context.setLineDash([8,8]);context.strokeStyle="#ffc25e";context.lineWidth=3;for(const [start,end] of GAP_RANGES){context.beginPath();for(let i=0;i<=12;i++){const point=project(this.curve.getPointAt(start+(end-start)*i/12));if(i===0)context.moveTo(point.x,point.y);else context.lineTo(point.x,point.y);}context.stroke();}context.setLineDash([]);this.activeRivals().forEach(rival=>{const rivalProgress=((rival.distance/this.trackLength)%1+1)%1,point=mapPoint(rivalProgress,rival.lane);context.fillStyle=`#${rival.color.toString(16).padStart(6,"0")}`;context.beginPath();context.arc(point.x,point.y,6,0,Math.PI*2);context.fill();});const player=mapPoint(progress,this.lateral);context.fillStyle="#ff3e93";context.shadowColor="#ff3e93";context.shadowBlur=14;context.beginPath();context.arc(player.x,player.y,9,0,Math.PI*2);context.fill();context.shadowBlur=0;context.fillStyle="#dffeff";context.font="700 18px monospace";context.fillText(trackSector(progress).toUpperCase(),22,28);this.mapTexture.needsUpdate=true;}
  private resize(){const width=this.canvas.clientWidth||innerWidth,height=this.canvas.clientHeight||innerHeight;this.renderer.setSize(width,height,false);this.camera.aspect=width/Math.max(1,height);this.camera.updateProjectionMatrix();}
  destroy(){this.destroyed=true;this.renderer.setAnimationLoop(null);this.listeners.forEach(dispose=>dispose());this.audio.destroy();this.renderer.dispose();}
}
