"use client";

import { useEffect,useRef,useState,type CSSProperties,type ReactNode } from "react";
import * as THREE from "three";
import { DEFAULT_AUDIO_SETTINGS,loadAudioSettings,saveAudioSettings,type AudioSettings } from "./audio";
import { createRacer,FZoneEngine } from "./engine";
import { GAME_MODES,SHIPS,STORY_EVENTS,TRACKS,type GameModeId,type MenuScreen,type ShipSpec,type StoryEvent } from "./game-data";
import { formatTime } from "./mechanics";
import { getTrackLayout,isGap } from "./track-data";
import { INITIAL_SNAPSHOT,type OpponentMarker,type RaceSnapshot } from "./types";

function TrackMap({trackId,progress,opponents}:{trackId:string;progress:number;opponents:OpponentMarker[]}){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=canvasRef.current,context=canvas?.getContext("2d");if(!canvas||!context)return;
    const layout=getTrackLayout(trackId),curve=new THREE.CatmullRomCurve3(layout.points.map(point=>new THREE.Vector3(...point)),true,"centripetal"),width=canvas.width,height=canvas.height,samples=Array.from({length:241},(_,index)=>curve.getPointAt(index/240)),minX=Math.min(...samples.map(point=>point.x)),maxX=Math.max(...samples.map(point=>point.x)),minZ=Math.min(...samples.map(point=>point.z)),maxZ=Math.max(...samples.map(point=>point.z)),spanX=Math.max(1,maxX-minX),spanZ=Math.max(1,maxZ-minZ),scale=Math.min((width-48)/spanX,(height-40)/spanZ),offsetX=(width-spanX*scale)/2,offsetY=(height-spanZ*scale)/2;
    const project=(point:{x:number;z:number})=>({x:offsetX+(point.x-minX)*scale,y:height-offsetY-(point.z-minZ)*scale}),mapPoint=(p:number,lane=0)=>{const center=curve.getPointAt(p),tangent=curve.getTangentAt(p).normalize(),right=new THREE.Vector3(-tangent.z,0,tangent.x).normalize();return project(center.clone().addScaledVector(right,lane));};
    context.clearRect(0,0,width,height);context.fillStyle="rgba(2,12,20,.94)";context.fillRect(0,0,width,height);
    context.strokeStyle="rgba(105,246,255,.12)";context.lineWidth=1;for(let x=0;x<width;x+=24){context.beginPath();context.moveTo(x,0);context.lineTo(x,height);context.stroke();}for(let y=0;y<height;y+=24){context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke();}
    context.strokeStyle="#69f6ff";context.lineWidth=6;context.lineJoin="round";context.lineCap="round";let drawing=false;for(let index=0;index<=240;index++){const p=index/240;if(isGap(p,layout)){if(drawing)context.stroke();drawing=false;continue;}const mapped=project(samples[index]);if(!drawing){context.beginPath();context.moveTo(mapped.x,mapped.y);drawing=true;}else context.lineTo(mapped.x,mapped.y);}if(drawing)context.stroke();
    context.strokeStyle="#ffc25e";context.lineWidth=3;context.setLineDash([7,6]);for(const [start,end] of layout.gaps){context.beginPath();for(let index=0;index<=12;index++){const mapped=project(curve.getPointAt(start+(end-start)*index/12));if(index===0)context.moveTo(mapped.x,mapped.y);else context.lineTo(mapped.x,mapped.y);}context.stroke();}context.setLineDash([]);
    context.strokeStyle="#4dffb8";context.lineWidth=4;for(const [start,end] of layout.energy){context.beginPath();for(let index=0;index<=14;index++){const mapped=project(curve.getPointAt(start+(end-start)*index/14));if(index===0)context.moveTo(mapped.x,mapped.y);else context.lineTo(mapped.x,mapped.y);}context.stroke();}
    opponents.forEach(opponent=>{const marker=mapPoint(opponent.progress,opponent.lane);context.fillStyle=opponent.color;context.strokeStyle="#031018";context.lineWidth=2;context.beginPath();context.arc(marker.x,marker.y,4.5,0,Math.PI*2);context.fill();context.stroke();});
    const player=mapPoint(progress);context.fillStyle=isGap(progress,layout)?"#ffc25e":"#ff3e93";context.shadowColor=context.fillStyle;context.shadowBlur=12;context.beginPath();context.arc(player.x,player.y,7,0,Math.PI*2);context.fill();context.shadowBlur=0;
  },[opponents,progress,trackId]);
  return <canvas ref={canvasRef} width={360} height={300} className="track-map-canvas" aria-label={`Minimapa do circuito ${getTrackLayout(trackId).name}`}/>;
}

function ShipHangarPreview({ship}:{ship:ShipSpec}){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=canvasRef.current;if(!canvas)return;
    const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;
    const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,100),variant=Math.max(0,SHIPS.findIndex(candidate=>candidate.id===ship.id)),model=createRacer(ship,variant);camera.position.set(7.4,5.3,8.8);camera.lookAt(0,.2,0);model.rotation.x=-.08;scene.add(model,new THREE.HemisphereLight(0xc8faff,0x07030f,2.4));const key=new THREE.DirectionalLight(0xffffff,4.2);key.position.set(4,8,3);scene.add(key);const rim=new THREE.PointLight(ship.accent,18,18);rim.position.set(-4,2,-4);scene.add(rim);
    const grid=new THREE.GridHelper(14,28,new THREE.Color(ship.accent),new THREE.Color(0x12303b));grid.position.y=-.18;(grid.material as THREE.Material).transparent=true;(grid.material as THREE.Material).opacity=.24;scene.add(grid);
    let frame=0,last=performance.now();const resize=()=>{const width=Math.max(1,canvas.clientWidth),height=Math.max(1,canvas.clientHeight);if(canvas.width!==Math.round(width*renderer.getPixelRatio())||canvas.height!==Math.round(height*renderer.getPixelRatio()))renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();};
    const animate=(now:number)=>{const dt=Math.min(.05,(now-last)/1000);last=now;model.rotation.y+=dt*.38;model.position.y=.12+Math.sin(now*.0014)*.06;resize();renderer.render(scene,camera);frame=requestAnimationFrame(animate);};frame=requestAnimationFrame(animate);
    return()=>{cancelAnimationFrame(frame);model.traverse(object=>{if(!(object instanceof THREE.Mesh))return;object.geometry.dispose();const materials=Array.isArray(object.material)?object.material:[object.material];materials.forEach(material=>material.dispose());});renderer.dispose();};
  },[ship]);
  return <canvas ref={canvasRef} className="ship-hangar-canvas" aria-label={`Prévia tridimensional rotativa da nave ${ship.name}`}/>;
}

export function FZoneGame(){
  const canvasRef=useRef<HTMLCanvasElement>(null),engineRef=useRef<FZoneEngine|null>(null);const [race,setRace]=useState<RaceSnapshot>(INITIAL_SNAPSHOT),[xrError,setXrError]=useState(""),[audioOpen,setAudioOpen]=useState(false),[audioSettings,setAudioSettings]=useState<AudioSettings>(DEFAULT_AUDIO_SETTINGS),[menuScreen,setMenuScreen]=useState<MenuScreen>("entry"),[preferredLaunch,setPreferredLaunch]=useState<"vr"|"screen">("vr"),[modeId,setModeId]=useState<GameModeId>("story"),[storyEventIndex,setStoryEventIndex]=useState(0),[shipId,setShipId]=useState(SHIPS[0].id),[trackId,setTrackId]=useState(TRACKS[0].id);
  useEffect(()=>{if(!canvasRef.current)return;const settings=loadAudioSettings(),engine=new FZoneEngine(canvasRef.current,setRace);engine.setAudioSettings(settings);setAudioSettings(settings);engineRef.current=engine;return()=>{engine.destroy();engineRef.current=null;};},[]);
  const toggleMap=()=>engineRef.current?.toggleMinimap();
  const enterVRLobby=()=>{const engine=engineRef.current;if(!engine)return;setPreferredLaunch("vr");setXrError("");void engine.enterVRLobby().catch(error=>setXrError(error instanceof Error?error.message:"Não foi possível abrir o espaço VR"));};
  const enterVR=()=>{const engine=engineRef.current;if(!engine)return;engine.configureRace(modeId,shipId,storyEventIndex,trackId);setXrError("");void engine.enterVR().catch(error=>setXrError(error instanceof Error?error.message:"Não foi possível iniciar o modo VR"));};
  const changeAudio=(key:keyof AudioSettings,value:number|boolean)=>{const next={...audioSettings,[key]:value};setAudioSettings(next);saveAudioSettings(next);engineRef.current?.setAudioSettings(next);};
  const startRace=()=>{engineRef.current?.configureRace(modeId,shipId,storyEventIndex,trackId);engineRef.current?.start();},returnToMenu=()=>{engineRef.current?.returnToMenu();setMenuScreen("entry");},relaunchRace=(eventIndex:number)=>{const engine=engineRef.current;if(!engine)return;engine.configureRace(modeId,shipId,eventIndex,race.trackId);if(race.inputMode==="vr"){setXrError("");void engine.enterVR().catch(error=>setXrError(error instanceof Error?error.message:"Não foi possível reiniciar o modo VR"));}else engine.start();},retryRace=()=>relaunchRace(storyEventIndex),advanceAfterRace=()=>{if(modeId==="story"&&race.position<=3&&storyEventIndex<STORY_EVENTS.length-1){const next=storyEventIndex+1;setStoryEventIndex(next);relaunchRace(next);return;}returnToMenu();},selectedMode=GAME_MODES.find(mode=>mode.id===modeId)??GAME_MODES[0],selectedShip=SHIPS.find(ship=>ship.id===shipId)??SHIPS[0],selectedTrack=TRACKS.find(track=>track.id===trackId)??TRACKS[0],selectedStoryEvent=STORY_EVENTS[storyEventIndex];
  const displaySpeed=race.displaySpeed,nearestOpponents=[...race.opponents].sort((a,b)=>Math.abs(a.delta)-Math.abs(b.delta)).slice(0,3);
  return <main className="fz-shell">
    <canvas ref={canvasRef} className="fz-canvas" aria-label="F-Zone VR, corrida antigravidade futurista"/><div className="fz-grain"/><div className={`boost-fx ${race.boosting?"active":""}`} aria-hidden="true"/><div key={race.impactPulse} className={`fz-vignette ${race.impactPulse?"hit":""}`}/>
    {race.phase!=="menu"&&<section className="race-hud" aria-live="polite">
      <div className="race-top"><div><div className="race-brand"><i/> F-Zone VR</div><div className="race-sector">Circuito 01 · {race.sector}</div></div><div className="race-standing"><div className="race-position">Posição<strong>{race.position}<span>/{race.racers}</span></strong></div><div className="opponent-radar">{nearestOpponents.map(opponent=><div key={`${opponent.color}-${opponent.place}`}><i style={{background:opponent.color}}/><b>P{opponent.place}</b><span>{opponent.delta>=0?"+":"−"}{Math.round(Math.abs(opponent.delta))} m</span></div>)}</div></div></div>
      <button className={`map-toggle ${race.minimapVisible?"active":""}`} onClick={toggleMap} aria-pressed={race.minimapVisible}>M · Mapa</button>
      {race.minimapVisible&&<aside className="minimap-shell"><div className="minimap-title"><span>{race.trackName}</span><b>{race.airborne?"SALTO":race.magnetic?"MAG-LOCK":"ONLINE"}</b></div><TrackMap trackId={race.trackId} progress={race.progress} opponents={race.opponents}/><div className="minimap-legend"><span><i className="map-you"/>Você</span><span><i className="map-rival"/>Rivais</span><span><i className="map-gap"/>Trecho aéreo</span></div></aside>}
      <div className="speed-hud"><div className="speed-label">Velocidade</div><div className="speed-number"><strong>{displaySpeed}</strong><span><b>km/h</b><small>{race.boosting?"Nitro":race.energyCharging?"Recarga":"Propulsão"}</small></span></div>{(race.drafting||race.drifting||race.boosting||race.energyCharging)&&<div className={`race-technique ${race.drafting?"drafting":""} ${race.boosting?"nitro":""} ${race.energyCharging?"charging":""}`}>{race.boosting?"Nitro ativo":race.energyCharging?"Recarga lateral":race.drafting?"Vácuo ativo + velocidade":"Derrapagem"}</div>}<div className="energy-label"><span>Fluxo de impulso</span><b>{Math.round(race.boost)}%</b></div><div className="energy-track"><div className={`energy-fill ${race.boost<24?"low":""} ${race.energyCharging?"charging":""}`} style={{width:`${race.boost}%`}}/></div></div>
      <div className="lap-hud"><small>Volta {race.lap}/{race.totalLaps}</small><b>{formatTime(race.lapTime)}</b><span>Melhor {race.bestLap===null?"--:--.--":formatTime(race.bestLap)}</span></div>{race.message&&<div key={race.messagePulse} className="race-message">{race.message}</div>}
    </section>}
    {race.phase==="menu"&&<MenuFlow screen={menuScreen} setScreen={setMenuScreen} preferredLaunch={preferredLaunch} setPreferredLaunch={setPreferredLaunch} modeId={modeId} setModeId={setModeId} setStoryEventIndex={setStoryEventIndex} shipId={shipId} setShipId={setShipId} trackId={trackId} setTrackId={setTrackId} selectedMode={selectedMode} selectedShip={selectedShip} selectedTrack={selectedTrack} selectedStoryEvent={selectedStoryEvent} race={race} xrError={xrError} enterVRLobby={enterVRLobby} enterVR={enterVR} startRace={startRace} openAudio={()=>setAudioOpen(true)}/>}
    {race.phase==="paused"&&<SimpleOverlay eyebrow="Sistema suspenso" title="Pausa" text="A corrida e o áudio do motor estão pausados."><button className="fz-button" onClick={()=>engineRef.current?.start()}>Retomar</button><button className="fz-button secondary" onClick={()=>setAudioOpen(true)}>Áudio</button><button className="fz-button secondary" onClick={returnToMenu}>Sair para o menu</button></SimpleOverlay>}
    {race.phase==="finished"&&<ResultsOverlay race={race} selectedMode={selectedMode.name} selectedShip={selectedShip.name} storyEvent={modeId==="story"?selectedStoryEvent:null} storyEventIndex={storyEventIndex} retry={retryRace} continueRace={advanceAfterRace}/>}
    {audioOpen&&<section className="audio-settings-overlay"><button className="audio-settings-backdrop" type="button" onClick={()=>setAudioOpen(false)} aria-label="Fechar configurações de áudio"/><div className="audio-settings-panel" role="dialog" aria-modal="true" aria-labelledby="audio-settings-title"><div className="audio-settings-head"><div><small>Preferências</small><h2 id="audio-settings-title">Áudio</h2></div><button type="button" onClick={()=>setAudioOpen(false)} aria-label="Fechar configurações de áudio">×</button></div><AudioSlider label="Volume geral" value={audioSettings.master} onChange={value=>changeAudio("master",value)}/><AudioSlider label="Música" value={audioSettings.music} onChange={value=>changeAudio("music",value)}/><AudioSlider label="Efeitos e motor" value={audioSettings.sfx} onChange={value=>changeAudio("sfx",value)}/><label className="audio-mute"><input type="checkbox" checked={audioSettings.muted} onChange={event=>changeAudio("muted",event.target.checked)}/><span>Silenciar tudo</span></label><p>As preferências ficam salvas neste dispositivo.</p></div></section>}
  </main>;
}

function MenuFrame({step,title,subtitle,children,back}:{step:string;title:string;subtitle:string;children:ReactNode;back?:()=>void}){return <section className="fz-overlay selection-overlay"><div className="fz-grid"/><div className="selection-shell"><header className="selection-head"><div><div className="fz-eyebrow">{step}</div><h2>{title}</h2><p>{subtitle}</p></div>{back&&<button className="selection-back" onClick={back}>← Voltar</button>}</header>{children}</div></section>;}

function MenuFlow({screen,setScreen,preferredLaunch,setPreferredLaunch,modeId,setModeId,setStoryEventIndex,shipId,setShipId,trackId,setTrackId,selectedMode,selectedShip,selectedTrack,selectedStoryEvent,race,xrError,enterVRLobby,enterVR,startRace,openAudio}:{screen:MenuScreen;setScreen:(screen:MenuScreen)=>void;preferredLaunch:"vr"|"screen";setPreferredLaunch:(target:"vr"|"screen")=>void;modeId:GameModeId;setModeId:(mode:GameModeId)=>void;setStoryEventIndex:(index:number)=>void;shipId:string;setShipId:(id:string)=>void;trackId:string;setTrackId:(id:string)=>void;selectedMode:(typeof GAME_MODES)[number];selectedShip:ShipSpec;selectedTrack:(typeof TRACKS)[number];selectedStoryEvent:StoryEvent;race:RaceSnapshot;xrError:string;enterVRLobby:()=>void;enterVR:()=>void;startRace:()=>void;openAudio:()=>void}){
  if(screen==="entry")return <section className="fz-overlay"><div className="fz-grid"/><div className="fz-brief entry-brief"><div className="fz-eyebrow">Liga experimental · Temporada zero</div><h1>F-Zone<span>Virtual velocity</span></h1><div className="fz-line"/><p>Prepare sua nave antigravidade, escolha o campeonato e entre no circuito pelo navegador ou pelo Meta Quest.</p><div className="fz-actions"><button className="fz-button" disabled={!race.vrChecked||race.vrActive} onClick={enterVRLobby}>{race.vrActive?"VR ativo":"Entrar em VR"}</button><button className="fz-button secondary" onClick={()=>{setPreferredLaunch("screen");setScreen("mode");}}>Jogar na tela</button><button className="fz-button secondary" onClick={openAudio}>Opções</button></div><div className={`fz-status ${xrError?"error":""}`}>{xrError||(!race.vrChecked?"Preparando o acesso imersivo…":"No VR, modo, nave, pista e resultados permanecem dentro do espaço imersivo.")}</div></div></section>;
  if(screen==="mode")return <MenuFrame step="Liga experimental · Temporada zero" title="F-Zone VR" subtitle="Escolha como você quer correr."><div className="mode-grid">{GAME_MODES.map(mode=><button key={mode.id} className={`mode-card ${mode.id===modeId?"selected":""}`} onClick={()=>{setModeId(mode.id);if(mode.id==="story")setStoryEventIndex(0);setScreen("ship");}}><small>{mode.kicker}</small><strong>{mode.name}</strong><p>{mode.description}</p><b>{mode.badge}</b></button>)}<button className="mode-card utility" onClick={openAudio}><small>Sistema</small><strong>Opções</strong><p>Ajuste volume geral, música e efeitos da nave.</p><b>Áudio</b></button><button className="mode-card utility" disabled><small>Futuro</small><strong>VS</strong><p>Estrutura reservada para corrida entre jogadores.</p><b>Em breve</b></button></div></MenuFrame>;
  if(screen==="ship")return <MenuFrame step={`02 · ${selectedMode.name}`} title="Escolha sua nave" subtitle="Compare a arquitetura e os atributos da máquina antes de confirmar. O modelo exibido aqui é o mesmo usado na corrida." back={()=>setScreen("mode")}><div className="ship-hangar"><div className="ship-hangar-stage" style={{"--ship-accent":selectedShip.accent} as CSSProperties}><ShipHangarPreview ship={selectedShip}/><div className="ship-hangar-id"><small>{selectedShip.role} · Chassi {String(SHIPS.findIndex(ship=>ship.id===selectedShip.id)+1).padStart(2,"0")}</small><strong>{selectedShip.name}</strong><span>Modelo de corrida · visualização 360°</span></div><div className="ship-hangar-stats"><ShipStats ship={selectedShip}/></div></div><div className="ship-roster">{SHIPS.map((ship,index)=><button key={ship.id} className={`ship-card ${ship.id===shipId?"selected":""}`} style={{"--ship-accent":ship.accent} as CSSProperties} onClick={()=>setShipId(ship.id)}><span className="ship-index">{String(index+1).padStart(2,"0")}</span><span className="ship-card-copy"><small>{ship.role}</small><strong>{ship.name}</strong></span></button>)}</div><div className="selection-actions"><span>Chassi selecionado: {selectedShip.name}</span><button className="fz-button" onClick={()=>setScreen("track")}>Confirmar nave</button></div></div></MenuFrame>;
  return <MenuFrame step={`03 · ${selectedMode.name} · ${selectedShip.name}`} title="Escolha a pista" subtitle="Circuitos futuros já aparecem na liga, mas serão liberados conforme a fila de desenvolvimento." back={()=>setScreen("ship")}><div className="track-grid">{TRACKS.map(track=><button key={track.id} disabled={!track.available} className={`track-card ${track.id===trackId?"selected":""}`} onClick={()=>setTrackId(track.id)}><div className="track-map-mark"><i/><i/><i/></div><small>{track.region}</small><strong>{track.name}</strong><p>{track.description}</p><div><span>{track.laps} voltas</span><span>Dificuldade {track.difficulty}/5</span></div><div className="track-features">{track.features.map(feature=><span key={feature}>{feature}</span>)}</div>{!track.available&&<b>Em construção</b>}</button>)}</div><div className="race-briefing"><div><small>{modeId==="story"?`História ${selectedStoryEvent.chapter}/${STORY_EVENTS.length}`:"Configuração de largada"}</small><strong>{modeId==="story"?selectedStoryEvent.title:`${selectedMode.name} · ${selectedShip.name} · ${selectedTrack.name}`}</strong><span>{modeId==="story"?`${selectedStoryEvent.briefing} Rival: ${selectedStoryEvent.rival}. ${selectedStoryEvent.laps} voltas.`:selectedMode.rivals?"6 competidores":"Contra o relógio · sem rivais"}</span></div><div className="fz-actions">{preferredLaunch==="vr"?<><button className="fz-button" disabled={!race.vrChecked||race.vrActive} onClick={enterVR}>{race.vrActive?"VR ativo":!race.vrChecked?"Preparando WebXR":race.vrSupported?"Entrar em VR":"Tentar entrar em VR"}</button><button className="fz-button secondary" onClick={startRace}>Correr na tela</button></>:<><button className="fz-button" onClick={startRace}>Correr na tela</button><button className="fz-button secondary" disabled={!race.vrChecked||race.vrActive} onClick={enterVR}>Entrar em VR</button></>}<button className="fz-button secondary" onClick={openAudio}>Áudio</button></div><div className={`fz-status ${xrError?"error":""}`}>{xrError||(!race.vrChecked?"Preparando o acesso imersivo":race.vrSupported?"Meta Quest detectado · pronto para largar":race.vrApiAvailable?"API WebXR presente · tentativa direta liberada":"WebXR não detectado · use o Meta Quest Browser em HTTPS")}</div></div></MenuFrame>;
}

function ShipStats({ship}:{ship:ShipSpec}){const stats=[["Aceleração",ship.stats.acceleration],["Velocidade",ship.stats.topSpeed],["Controle",ship.stats.handling],["Impulso",ship.stats.boost],["Resistência",ship.stats.body]] as const;return <div className="ship-stats">{stats.map(([label,value])=><div key={label}><span>{label}</span><i>{Array.from({length:5},(_,index)=><b key={index} className={index<value?"on":""}/>)}</i></div>)}</div>;}

function SimpleOverlay({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:ReactNode}){return <section className="fz-overlay"><div className="fz-grid"/><div className="simple-panel"><div className="fz-eyebrow">{eyebrow}</div><h2>{title}</h2><p>{text}</p><div className="fz-actions">{children}</div></div></section>;}

function ResultsOverlay({race,selectedMode,selectedShip,storyEvent,storyEventIndex,retry,continueRace}:{race:RaceSnapshot;selectedMode:string;selectedShip:string;storyEvent:StoryEvent|null;storyEventIndex:number;retry:()=>void;continueRace:()=>void}){const standings=[{place:race.position,name:selectedShip,color:"#ff3e93",player:true},...race.opponents.map(opponent=>({place:opponent.place,name:opponent.name,color:opponent.color,player:false}))].sort((a,b)=>a.place-b.place),podium=race.position<=3,storyComplete=Boolean(storyEvent&&podium&&storyEventIndex===STORY_EVENTS.length-1),canAdvance=Boolean(storyEvent&&podium&&!storyComplete);return <section className="fz-overlay results-overlay"><div className="fz-grid"/><div className="results-panel"><header><div><div className="fz-eyebrow">Resultado oficial · {selectedMode}{storyEvent?` · Evento ${storyEvent.chapter}`:""}</div><h2>{storyComplete?"Temporada concluída":podium?"Pódio confirmado":"Prova concluída"}</h2><p>{storyComplete?"Você conquistou a Coroa Solar.":podium?"Resultado válido para progressão.":"No modo História será necessário terminar entre os três primeiros."}</p></div><div className="result-position"><span>Posição</span><strong>{race.position}<small>/{race.racers}</small></strong></div></header><div className="results-table">{standings.map(entry=><div key={`${entry.name}-${entry.place}`} className={entry.player?"player":""}><b>{String(entry.place).padStart(2,"0")}</b><i style={{background:entry.color}}/><strong>{entry.name}</strong><span>{entry.player?"Você":"Finalizou"}</span></div>)}</div><footer><div><small>Melhor volta</small><strong>{race.bestLap===null?"--:--.--":formatTime(race.bestLap)}</strong></div><div className="fz-actions"><button className="fz-button secondary" onClick={retry}>Correr novamente</button><button className="fz-button" onClick={continueRace}>{canAdvance?"Próxima corrida":storyComplete?"Concluir história":"Voltar ao menu"}</button></div></footer></div></section>;}

function AudioSlider({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className="audio-setting"><span>{label}</span><input type="range" min="0" max="100" step="1" value={Math.round(value*100)} onChange={event=>onChange(Number(event.target.value)/100)}/><b>{Math.round(value*100)}%</b></label>;}
