"use client";

import { useEffect,useRef,useState,type ReactNode } from "react";
import * as THREE from "three";
import { DEFAULT_AUDIO_SETTINGS,loadAudioSettings,saveAudioSettings,type AudioSettings } from "./audio";
import { FZoneEngine } from "./engine";
import { GAME_MODES,SHIPS,TRACKS,type GameModeId,type MenuScreen,type ShipSpec } from "./game-data";
import { formatTime } from "./mechanics";
import { GAP_RANGES,TRACK_POINTS,isGap } from "./track-data";
import { INITIAL_SNAPSHOT,type OpponentMarker,type RaceSnapshot } from "./types";

const MAP_CURVE=new THREE.CatmullRomCurve3(TRACK_POINTS.map(point=>new THREE.Vector3(...point)),true,"centripetal");

function TrackMap({progress,opponents}:{progress:number;opponents:OpponentMarker[]}){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{
    const canvas=canvasRef.current,context=canvas?.getContext("2d");if(!canvas||!context)return;
    const width=canvas.width,height=canvas.height;
    const project=(point:{x:number;z:number})=>({x:24+(point.x+250)/530*(width-48),y:20+(210-point.z)/385*(height-40)}),mapPoint=(p:number,lane=0)=>{const center=MAP_CURVE.getPointAt(p),tangent=MAP_CURVE.getTangentAt(p).normalize(),right=new THREE.Vector3(-tangent.z,0,tangent.x).normalize();return project(center.clone().addScaledVector(right,lane));};
    context.clearRect(0,0,width,height);context.fillStyle="rgba(2,12,20,.94)";context.fillRect(0,0,width,height);
    context.strokeStyle="rgba(105,246,255,.12)";context.lineWidth=1;for(let x=0;x<width;x+=24){context.beginPath();context.moveTo(x,0);context.lineTo(x,height);context.stroke();}for(let y=0;y<height;y+=24){context.beginPath();context.moveTo(0,y);context.lineTo(width,y);context.stroke();}
    context.strokeStyle="#69f6ff";context.lineWidth=6;context.lineJoin="round";context.lineCap="round";let drawing=false;for(let index=0;index<=240;index++){const p=index/240;if(isGap(p)){if(drawing)context.stroke();drawing=false;continue;}const mapped=project(MAP_CURVE.getPointAt(p));if(!drawing){context.beginPath();context.moveTo(mapped.x,mapped.y);drawing=true;}else context.lineTo(mapped.x,mapped.y);}if(drawing)context.stroke();
    context.strokeStyle="#ffc25e";context.lineWidth=3;context.setLineDash([7,6]);for(const [start,end] of GAP_RANGES){context.beginPath();for(let index=0;index<=12;index++){const mapped=project(MAP_CURVE.getPointAt(start+(end-start)*index/12));if(index===0)context.moveTo(mapped.x,mapped.y);else context.lineTo(mapped.x,mapped.y);}context.stroke();}context.setLineDash([]);
    opponents.forEach(opponent=>{const marker=mapPoint(opponent.progress,opponent.lane);context.fillStyle=opponent.color;context.strokeStyle="#031018";context.lineWidth=2;context.beginPath();context.arc(marker.x,marker.y,4.5,0,Math.PI*2);context.fill();context.stroke();});
    const player=mapPoint(progress);context.fillStyle=isGap(progress)?"#ffc25e":"#ff3e93";context.shadowColor=context.fillStyle;context.shadowBlur=12;context.beginPath();context.arc(player.x,player.y,7,0,Math.PI*2);context.fill();context.shadowBlur=0;
  },[opponents,progress]);
  return <canvas ref={canvasRef} width={360} height={300} className="track-map-canvas" aria-label="Minimapa do circuito Helix Verge"/>;
}

export function FZoneGame(){
  const canvasRef=useRef<HTMLCanvasElement>(null),engineRef=useRef<FZoneEngine|null>(null);const [race,setRace]=useState<RaceSnapshot>(INITIAL_SNAPSHOT),[xrError,setXrError]=useState(""),[audioOpen,setAudioOpen]=useState(false),[audioSettings,setAudioSettings]=useState<AudioSettings>(DEFAULT_AUDIO_SETTINGS),[menuScreen,setMenuScreen]=useState<MenuScreen>("entry"),[preferredLaunch,setPreferredLaunch]=useState<"vr"|"screen">("vr"),[modeId,setModeId]=useState<GameModeId>("story"),[shipId,setShipId]=useState(SHIPS[0].id),[trackId,setTrackId]=useState(TRACKS[0].id);
  useEffect(()=>{if(!canvasRef.current)return;const settings=loadAudioSettings(),engine=new FZoneEngine(canvasRef.current,setRace);engine.setAudioSettings(settings);setAudioSettings(settings);engineRef.current=engine;return()=>{engine.destroy();engineRef.current=null;};},[]);
  const toggleMap=()=>engineRef.current?.toggleMinimap();
  const enterVR=()=>{const engine=engineRef.current;if(!engine)return;engine.configureRace(modeId,shipId);setXrError("");void engine.enterVR().catch(error=>setXrError(error instanceof Error?error.message:"Não foi possível iniciar o modo VR"));};
  const changeAudio=(key:keyof AudioSettings,value:number|boolean)=>{const next={...audioSettings,[key]:value};setAudioSettings(next);saveAudioSettings(next);engineRef.current?.setAudioSettings(next);};
  const startRace=()=>{engineRef.current?.configureRace(modeId,shipId);engineRef.current?.start();},returnToMenu=()=>{engineRef.current?.returnToMenu();setMenuScreen("entry");},selectedMode=GAME_MODES.find(mode=>mode.id===modeId)??GAME_MODES[0],selectedShip=SHIPS.find(ship=>ship.id===shipId)??SHIPS[0],selectedTrack=TRACKS.find(track=>track.id===trackId)??TRACKS[0];
  const displaySpeed=race.displaySpeed,nearestOpponents=[...race.opponents].sort((a,b)=>Math.abs(a.delta)-Math.abs(b.delta)).slice(0,3);
  return <main className="fz-shell">
    <canvas ref={canvasRef} className="fz-canvas" aria-label="F-Zone VR, corrida antigravidade futurista"/><div className="fz-grain"/><div className={`boost-fx ${race.boosting?"active":""}`} aria-hidden="true"/><div key={race.impactPulse} className={`fz-vignette ${race.impactPulse?"hit":""}`}/>
    {race.phase!=="menu"&&<section className="race-hud" aria-live="polite">
      <div className="race-top"><div><div className="race-brand"><i/> F-Zone VR</div><div className="race-sector">Circuito 01 · {race.sector}</div></div><div className="race-standing"><div className="race-position">Posição<strong>{race.position}<span>/{race.racers}</span></strong></div><div className="opponent-radar">{nearestOpponents.map(opponent=><div key={`${opponent.color}-${opponent.place}`}><i style={{background:opponent.color}}/><b>P{opponent.place}</b><span>{opponent.delta>=0?"+":"−"}{Math.round(Math.abs(opponent.delta))} m</span></div>)}</div></div></div>
      <button className={`map-toggle ${race.minimapVisible?"active":""}`} onClick={toggleMap} aria-pressed={race.minimapVisible}>M · Mapa</button>
      {race.minimapVisible&&<aside className="minimap-shell"><div className="minimap-title"><span>Helix Verge</span><b>{race.airborne?"SALTO":race.magnetic?"MAG-LOCK":"ONLINE"}</b></div><TrackMap progress={race.progress} opponents={race.opponents}/><div className="minimap-legend"><span><i className="map-you"/>Você</span><span><i className="map-rival"/>Rivais</span><span><i className="map-gap"/>Trecho aéreo</span></div></aside>}
      <div className="speed-hud"><div className="speed-label">Velocidade</div><div className="speed-number"><strong>{displaySpeed}</strong><span><b>km/h</b><small>{race.boosting?"Nitro":"Propulsão"}</small></span></div>{(race.drafting||race.drifting||race.boosting)&&<div className={`race-technique ${race.drafting?"drafting":""} ${race.boosting?"nitro":""}`}>{race.boosting?"Nitro ativo":race.drafting?"Vácuo ativo + velocidade":"Derrapagem"}</div>}<div className="energy-label"><span>Fluxo de impulso</span><b>{Math.round(race.boost)}%</b></div><div className="energy-track"><div className={`energy-fill ${race.boost<24?"low":""}`} style={{width:`${race.boost}%`}}/></div></div>
      <div className="lap-hud"><small>Volta {race.lap}/{race.totalLaps}</small><b>{formatTime(race.lapTime)}</b><span>Melhor {race.bestLap===null?"--:--.--":formatTime(race.bestLap)}</span></div>{race.message&&<div key={race.messagePulse} className="race-message">{race.message}</div>}
    </section>}
    {race.phase==="menu"&&<MenuFlow screen={menuScreen} setScreen={setMenuScreen} preferredLaunch={preferredLaunch} setPreferredLaunch={setPreferredLaunch} modeId={modeId} setModeId={setModeId} shipId={shipId} setShipId={setShipId} trackId={trackId} setTrackId={setTrackId} selectedMode={selectedMode} selectedShip={selectedShip} selectedTrack={selectedTrack} race={race} xrError={xrError} enterVR={enterVR} startRace={startRace} openAudio={()=>setAudioOpen(true)}/>}
    {race.phase==="paused"&&<SimpleOverlay eyebrow="Sistema suspenso" title="Pausa" text="A corrida e o áudio do motor estão pausados."><button className="fz-button" onClick={()=>engineRef.current?.start()}>Retomar</button><button className="fz-button secondary" onClick={()=>setAudioOpen(true)}>Áudio</button><button className="fz-button secondary" onClick={returnToMenu}>Sair para o menu</button></SimpleOverlay>}
    {race.phase==="finished"&&<ResultsOverlay race={race} selectedMode={selectedMode.name} selectedShip={selectedShip.name} retry={startRace} continueRace={returnToMenu}/>}
    {audioOpen&&<section className="audio-settings-overlay"><button className="audio-settings-backdrop" type="button" onClick={()=>setAudioOpen(false)} aria-label="Fechar configurações de áudio"/><div className="audio-settings-panel" role="dialog" aria-modal="true" aria-labelledby="audio-settings-title"><div className="audio-settings-head"><div><small>Preferências</small><h2 id="audio-settings-title">Áudio</h2></div><button type="button" onClick={()=>setAudioOpen(false)} aria-label="Fechar configurações de áudio">×</button></div><AudioSlider label="Volume geral" value={audioSettings.master} onChange={value=>changeAudio("master",value)}/><AudioSlider label="Música" value={audioSettings.music} onChange={value=>changeAudio("music",value)}/><AudioSlider label="Efeitos e motor" value={audioSettings.sfx} onChange={value=>changeAudio("sfx",value)}/><label className="audio-mute"><input type="checkbox" checked={audioSettings.muted} onChange={event=>changeAudio("muted",event.target.checked)}/><span>Silenciar tudo</span></label><p>As preferências ficam salvas neste dispositivo.</p></div></section>}
  </main>;
}

function MenuFrame({step,title,subtitle,children,back}:{step:string;title:string;subtitle:string;children:ReactNode;back?:()=>void}){return <section className="fz-overlay selection-overlay"><div className="fz-grid"/><div className="selection-shell"><header className="selection-head"><div><div className="fz-eyebrow">{step}</div><h2>{title}</h2><p>{subtitle}</p></div>{back&&<button className="selection-back" onClick={back}>← Voltar</button>}</header>{children}</div></section>;}

function MenuFlow({screen,setScreen,preferredLaunch,setPreferredLaunch,modeId,setModeId,shipId,setShipId,trackId,setTrackId,selectedMode,selectedShip,selectedTrack,race,xrError,enterVR,startRace,openAudio}:{screen:MenuScreen;setScreen:(screen:MenuScreen)=>void;preferredLaunch:"vr"|"screen";setPreferredLaunch:(target:"vr"|"screen")=>void;modeId:GameModeId;setModeId:(mode:GameModeId)=>void;shipId:string;setShipId:(id:string)=>void;trackId:string;setTrackId:(id:string)=>void;selectedMode:(typeof GAME_MODES)[number];selectedShip:ShipSpec;selectedTrack:(typeof TRACKS)[number];race:RaceSnapshot;xrError:string;enterVR:()=>void;startRace:()=>void;openAudio:()=>void}){
  if(screen==="entry")return <section className="fz-overlay"><div className="fz-grid"/><div className="fz-brief entry-brief"><div className="fz-eyebrow">Liga experimental · Temporada zero</div><h1>F-Zone<span>Virtual velocity</span></h1><div className="fz-line"/><p>Prepare sua nave antigravidade, escolha o campeonato e entre no circuito pelo navegador ou pelo Meta Quest.</p><div className="fz-actions"><button className="fz-button" onClick={()=>{setPreferredLaunch("vr");setScreen("mode");}}>Entrar em VR</button><button className="fz-button secondary" onClick={()=>{setPreferredLaunch("screen");setScreen("mode");}}>Jogar na tela</button><button className="fz-button secondary" onClick={openAudio}>Opções</button></div><div className="fz-status">A seleção de modo, nave e pista acontece antes da largada.</div></div></section>;
  if(screen==="mode")return <MenuFrame step="Liga experimental · Temporada zero" title="F-Zone VR" subtitle="Escolha como você quer correr."><div className="mode-grid">{GAME_MODES.map(mode=><button key={mode.id} className={`mode-card ${mode.id===modeId?"selected":""}`} onClick={()=>{setModeId(mode.id);setScreen("ship");}}><small>{mode.kicker}</small><strong>{mode.name}</strong><p>{mode.description}</p><b>{mode.badge}</b></button>)}<button className="mode-card utility" onClick={openAudio}><small>Sistema</small><strong>Opções</strong><p>Ajuste volume geral, música e efeitos da nave.</p><b>Áudio</b></button><button className="mode-card utility" disabled><small>Futuro</small><strong>VS</strong><p>Estrutura reservada para corrida entre jogadores.</p><b>Em breve</b></button></div></MenuFrame>;
  if(screen==="ship")return <MenuFrame step={`02 · ${selectedMode.name}`} title="Escolha sua nave" subtitle="Toque em uma máquina para selecioná-la e avançar. Cada uma prioriza aceleração, velocidade, controle, impulso ou resistência." back={()=>setScreen("mode")}><div className="ship-grid">{SHIPS.map(ship=><button key={ship.id} className={`ship-card ${ship.id===shipId?"selected":""}`} onClick={()=>{setShipId(ship.id);setScreen("track");}}><div className="ship-visual"><i style={{background:ship.color,boxShadow:`0 0 30px ${ship.accent}55`}}/><span style={{background:ship.accent}}/><em style={{background:ship.accent}}/></div><div className="ship-copy"><small>{ship.role}</small><strong>{ship.name}</strong><ShipStats ship={ship}/></div></button>)}</div></MenuFrame>;
  return <MenuFrame step={`03 · ${selectedMode.name} · ${selectedShip.name}`} title="Escolha a pista" subtitle="Circuitos futuros já aparecem na liga, mas serão liberados conforme a fila de desenvolvimento." back={()=>setScreen("ship")}><div className="track-grid">{TRACKS.map(track=><button key={track.id} disabled={!track.available} className={`track-card ${track.id===trackId?"selected":""}`} onClick={()=>setTrackId(track.id)}><div className="track-map-mark"><i/><i/><i/></div><small>{track.region}</small><strong>{track.name}</strong><p>{track.description}</p><div><span>{track.laps} voltas</span><span>Dificuldade {track.difficulty}/5</span></div><div className="track-features">{track.features.map(feature=><span key={feature}>{feature}</span>)}</div>{!track.available&&<b>Em construção</b>}</button>)}</div><div className="race-briefing"><div><small>Configuração de largada</small><strong>{selectedMode.name} · {selectedShip.name} · {selectedTrack.name}</strong><span>{selectedMode.rivals?"6 competidores":"Contra o relógio · sem rivais"}</span></div><div className="fz-actions">{preferredLaunch==="vr"?<><button className="fz-button" disabled={!race.vrChecked||race.vrActive} onClick={enterVR}>{race.vrActive?"VR ativo":!race.vrChecked?"Preparando WebXR":race.vrSupported?"Entrar em VR":"Tentar entrar em VR"}</button><button className="fz-button secondary" onClick={startRace}>Correr na tela</button></>:<><button className="fz-button" onClick={startRace}>Correr na tela</button><button className="fz-button secondary" disabled={!race.vrChecked||race.vrActive} onClick={enterVR}>Entrar em VR</button></>}<button className="fz-button secondary" onClick={openAudio}>Áudio</button></div><div className={`fz-status ${xrError?"error":""}`}>{xrError||(!race.vrChecked?"Preparando o acesso imersivo":race.vrSupported?"Meta Quest detectado · pronto para largar":race.vrApiAvailable?"API WebXR presente · tentativa direta liberada":"WebXR não detectado · use o Meta Quest Browser em HTTPS")}</div></div></MenuFrame>;
}

function ShipStats({ship}:{ship:ShipSpec}){const stats=[["Aceleração",ship.stats.acceleration],["Velocidade",ship.stats.topSpeed],["Controle",ship.stats.handling],["Impulso",ship.stats.boost],["Resistência",ship.stats.body]] as const;return <div className="ship-stats">{stats.map(([label,value])=><div key={label}><span>{label}</span><i>{Array.from({length:5},(_,index)=><b key={index} className={index<value?"on":""}/>)}</i></div>)}</div>;}

function SimpleOverlay({eyebrow,title,text,children}:{eyebrow:string;title:string;text:string;children:ReactNode}){return <section className="fz-overlay"><div className="fz-grid"/><div className="simple-panel"><div className="fz-eyebrow">{eyebrow}</div><h2>{title}</h2><p>{text}</p><div className="fz-actions">{children}</div></div></section>;}

function ResultsOverlay({race,selectedMode,selectedShip,retry,continueRace}:{race:RaceSnapshot;selectedMode:string;selectedShip:string;retry:()=>void;continueRace:()=>void}){const standings=[{place:race.position,name:selectedShip,color:"#ff3e93",player:true},...race.opponents.map(opponent=>({place:opponent.place,name:opponent.name,color:opponent.color,player:false}))].sort((a,b)=>a.place-b.place),podium=race.position<=3;return <section className="fz-overlay results-overlay"><div className="fz-grid"/><div className="results-panel"><header><div><div className="fz-eyebrow">Resultado oficial · {selectedMode}</div><h2>{podium?"Pódio confirmado":"Prova concluída"}</h2><p>{podium?"Resultado válido para progressão.":"No modo História será necessário terminar entre os três primeiros."}</p></div><div className="result-position"><span>Posição</span><strong>{race.position}<small>/{race.racers}</small></strong></div></header><div className="results-table">{standings.map(entry=><div key={`${entry.name}-${entry.place}`} className={entry.player?"player":""}><b>{String(entry.place).padStart(2,"0")}</b><i style={{background:entry.color}}/><strong>{entry.name}</strong><span>{entry.player?"Você":"Finalizou"}</span></div>)}</div><footer><div><small>Melhor volta</small><strong>{race.bestLap===null?"--:--.--":formatTime(race.bestLap)}</strong></div><div className="fz-actions"><button className="fz-button secondary" onClick={retry}>Correr novamente</button><button className="fz-button" onClick={continueRace}>{podium?"Continuar":"Voltar ao menu"}</button></div></footer></div></section>;}

function AudioSlider({label,value,onChange}:{label:string;value:number;onChange:(value:number)=>void}){return <label className="audio-setting"><span>{label}</span><input type="range" min="0" max="100" step="1" value={Math.round(value*100)} onChange={event=>onChange(Number(event.target.value)/100)}/><b>{Math.round(value*100)}%</b></label>;}
